#!/usr/bin/env python3
"""Collect provenance-verified AW evidence and suggest deterministic TF-IDF clusters."""

import argparse
from collections import Counter
from datetime import datetime, timedelta, timezone
import json
import math
import os
from pathlib import Path
import re
import subprocess
import sys


WORKFLOW_ID = "aw-issue-clustering"
PREFIX = "[AW Top 10] "
CLUSTER_LABEL = "aw-essential"
OWNER_MARKER = f"<!-- gh-aw-workflow-id: {WORKFLOW_ID} -->"
START = "<!-- aw-essential-start -->"
END = "<!-- aw-essential-end -->"
META = re.compile(r"<!-- aw-essential-meta: (.+) -->")
STOP_WORDS = set("""
a an and are as at be been by can code daily for from gh github has have in is
it issue issues of on or report reports run runs that the this to was were with
workflow workflows generated agent agents test tests failed failure fix
""".split())


class GitHubAPIError(RuntimeError):
    def __init__(self, message, errors):
        super().__init__(message)
        self.errors = errors


def gh_json(*args, payload=None):
    command = ["gh", "api", *args]
    if payload is not None:
        command += ["--input", "-"]
    result = subprocess.run(
        command, input=json.dumps(payload) if payload is not None else None,
        text=True, capture_output=True,
    )
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise RuntimeError(f"GitHub API returned invalid JSON ({args[0]}): {result.stderr.strip()}") from error
    errors = data.get("errors", []) if isinstance(data, dict) else []
    if result.returncode or errors:
        raise GitHubAPIError(
            f"GitHub API request failed ({args[0]}): {result.stderr.strip() or errors or data}", errors,
        )
    return data


def graphql(document, **variables):
    return gh_json("graphql", payload={"query": document, "variables": variables})["data"]


def run_cutoff(repo):
    """A trusted run-start watermark keeps new arrivals for the next daily pass."""
    if os.environ.get("GITHUB_RUN_ID"):
        return gh_json(f"repos/{repo}/actions/runs/{os.environ['GITHUB_RUN_ID']}")["created_at"]
    return None


def bot_authored(item):
    author = item.get("user") or item.get("author") or {}
    return author.get("type", author.get("__typename")) == "Bot"


def aw_authored(item, repo):
    """Require bot authorship AND gh-aw provenance, never labels/title alone."""
    body = item.get("body") or ""
    run = re.search(
        rf"https://github\.com/{re.escape(repo)}/actions/runs/[0-9]+\b", body,
    )
    marker = re.search(r"<!-- gh-aw-(?:agentic-workflow|workflow-id|group):", body)
    legacy_footer = re.search(
        r"^> (?:AI generated by|Generated (?:by|from)) \[", body, re.MULTILINE,
    )
    return bot_authored(item) and bool(marker or (run and legacy_footer))


def owns_summary(item):
    body = item.get("body") or ""
    return (
        bot_authored(item) and OWNER_MARKER in body
        and item.get("title", "").startswith(PREFIX)
    )


def managed(item):
    body = item.get("body") or ""
    return owns_summary(item) and START in body and END in body and META.search(body) is not None


def metadata(item):
    return json.loads(META.search(item["body"]).group(1))


def collect_issues(repo, cutoff=None):
    pages = gh_json(
        f"repos/{repo}/issues?state=open&per_page=100", "--paginate", "--slurp",
    )
    closed = gh_json(
        f"repos/{repo}/issues?state=closed&labels={CLUSTER_LABEL}&per_page=100",
        "--paginate", "--slurp",
    )
    recent = gh_json(
        f"repos/{repo}/issues?state=closed&since={cutoff}&per_page=100",
        "--paginate", "--slurp",
    ) if cutoff else []
    return list({
        item["number"]: item for page in pages + closed + recent for item in page
        if "pull_request" not in item
    }.values())


DISCUSSION_FIELDS = """
number title body url createdAt updatedAt closed
author { login __typename } category { id name }
"""


def collect_discussions(repo, issues, days=14, now=None):
    owner, name = repo.split("/")
    cutoff = ((now or datetime.now(timezone.utc)) - timedelta(days=days)).strftime("%Y-%m-%dT%H:%M:%SZ")
    query = """
    query($owner:String!, $name:String!, $cursor:String) {
      repository(owner:$owner, name:$name) {
        discussions(first:100, after:$cursor,
          orderBy:{field:UPDATED_AT, direction:DESC}) {
          pageInfo { hasNextPage endCursor }
          nodes { %s }
        }
      }
    }
    """ % DISCUSSION_FIELDS
    discussions = {}
    cursor = None
    for _ in range(100):
        page = graphql(query, owner=owner, name=name, cursor=cursor)
        connection = page["repository"]["discussions"]
        for item in connection["nodes"]:
            if item["updatedAt"] >= cutoff and aw_authored(item, repo):
                discussions[item["number"]] = item
        if (
            not connection["pageInfo"]["hasNextPage"]
            or any(item["updatedAt"] < cutoff for item in connection["nodes"])
        ):
            break
        cursor = connection["pageInfo"]["endCursor"]
    else:
        raise ValueError("Discussion pagination exceeded 100 pages; refusing partial coverage")

    # Old briefings linked from still-open AW findings remain relevant evidence.
    linked = set()
    for issue in issues:
        linked.update(int(number) for number in re.findall(
            rf"https://github\.com/{re.escape(repo)}/discussions/([0-9]+)\b",
            issue.get("body") or "",
        ))
    query = """
    query($owner:String!, $name:String!, $number:Int!) {
      repository(owner:$owner, name:$name) { discussion(number:$number) { %s } }
    }
    """ % DISCUSSION_FIELDS
    for number in sorted(linked - discussions.keys()):
        try:
            item = graphql(query, owner=owner, name=name, number=number)["repository"]["discussion"]
        except GitHubAPIError as error:
            if error.errors and all(
                entry.get("type") == "NOT_FOUND" and entry.get("path") == ["repository", "discussion"]
                for entry in error.errors
            ):
                print(f"Linked discussion #{number} does not exist; excluded from evidence", file=sys.stderr)
                continue
            raise
        if item is not None and aw_authored(item, repo):
            discussions[number] = item
    return sorted(discussions.values(), key=lambda item: item["number"])


def build_corpus(repo, issues, discussions, cutoff=None):
    own, eligible, excluded = [], [], []
    completed = [
        item for item in issues
        if managed(item) and item.get("state") == "closed" and item.get("state_reason") == "completed"
    ]
    resolved_at = {}
    for item in completed:
        for number in metadata(item)["members"]:
            resolved_at[number] = max(resolved_at.get(number, ""), item["closed_at"])
    for issue in sorted(issues, key=lambda item: item["number"]):
        body = issue.get("body") or ""
        if issue.get("state", "open") != "open":
            continue
        if owns_summary(issue) and not managed(issue):
            raise ValueError(f"Owned summary #{issue['number']} has malformed metadata; refusing queue changes")
        if managed(issue):
            own.append(issue)
        elif cutoff and issue.get("created_at", "") > cutoff:
            excluded.append({"number": issue["number"], "reason": "Arrived after run start; next daily pass"})
        elif not aw_authored(issue, repo):
            excluded.append({"number": issue["number"], "reason": "No bot + AW provenance"})
        elif OWNER_MARKER in body:
            excluded.append({"number": issue["number"], "reason": "Clustering workflow output"})
        elif issue["number"] in resolved_at and issue.get("updated_at", "") <= resolved_at[issue["number"]]:
            excluded.append({"number": issue["number"], "reason": "Operator completed its cluster; no newer evidence"})
        elif issue["title"].startswith("[WIP] ") or "<!-- gh-aw-group:" in body:
            excluded.append({"number": issue["number"], "reason": "WIP or grouping container"})
        else:
            eligible.append(issue)
    reports = [
        item for item in discussions
        if aw_authored(item, repo) and OWNER_MARKER not in (item.get("body") or "")
    ]
    recently_closed = [
        item["number"] for item in issues
        if cutoff and item.get("state") == "closed"
        and item.get("closed_at", "") >= cutoff and item.get("created_at", "") <= cutoff
        and aw_authored(item, repo) and OWNER_MARKER not in (item.get("body") or "")
        and not item["title"].startswith("[WIP] ") and "<!-- gh-aw-group:" not in (item.get("body") or "")
    ]
    return {
        "repo": repo, "issues": eligible, "reports": reports, "managed": own,
        "excluded": excluded, "cutoff": cutoff, "completed": completed,
        "recently_closed": recently_closed,
    }


def features(item):
    body = item.get("body") or ""
    body = re.split(r"\n(?:> Generated|<!-- gh-aw-agentic-workflow)", body)[0]
    body = re.sub(r"https?://\S+|<!--.*?-->", " ", body, flags=re.DOTALL)
    text = (item["title"] + " ") * 3 + body[:5000]
    return Counter(
        word for word in re.findall(r"[a-z][a-z0-9_./-]{2,}", text.lower())
        if word not in STOP_WORDS and not word.startswith(("202", "http"))
    )


def vectors(items):
    counts = [features(item) for item in items]
    frequencies = Counter(word for terms in counts for word in terms)
    result = []
    for terms in counts:
        vector = {
            word: (1 + math.log(count)) * math.log(1 + len(items) / frequencies[word])
            for word, count in terms.items()
        }
        norm = math.sqrt(sum(value * value for value in vector.values())) or 1
        result.append({word: value / norm for word, value in vector.items()})
    return result


def similarity(left, right):
    return sum(value * right.get(word, 0) for word, value in left.items())


def seed_clusters(issues, limit=30):
    """Farthest-first seeds + medoid refinement; suggestions, NOT publication decisions."""
    if not issues:
        return []
    items = sorted(issues, key=lambda item: item["number"])
    points = vectors(items)
    centers = [0]
    while len(centers) < min(limit, len(items)):
        distances = [
            max(similarity(point, points[center]) for center in centers)
            if index not in centers else float("inf")
            for index, point in enumerate(points)
        ]
        centers.append(min(range(len(items)), key=lambda index: (distances[index], index)))
    for _ in range(4):
        groups = [[] for _ in centers]
        for index, point in enumerate(points):
            if index in centers:
                group = centers.index(index)
            else:
                group = max(range(len(centers)), key=lambda c: similarity(point, points[centers[c]]))
            groups[group].append(index)
        new_centers = [
            max(group, key=lambda candidate: sum(
                similarity(points[candidate], points[other]) for other in group
            ))
            for group in groups
        ]
        if centers == new_centers:
            break
        centers = new_centers
    return [
        {
            "members": [items[index]["number"] for index in group],
            "representative": items[center]["title"],
            "terms": sorted(points[center], key=points[center].get, reverse=True)[:8],
        }
        for center, group in zip(centers, groups)
    ]


def compact(item):
    body = item.get("body") or ""
    return {
        "number": item["number"], "title": item["title"], "url": item.get("html_url", item.get("url")),
        "updatedAt": item.get("updated_at", item.get("updatedAt")),
        "excerpt": body[:1400], "labels": [label["name"] for label in item.get("labels", [])],
    }


def write_evidence(corpus, output):
    output.mkdir(parents=True, exist_ok=True)
    (output / "corpus.json").write_text(json.dumps(corpus, ensure_ascii=True))
    for kind in ("issues", "reports"):
        directory = output / kind
        directory.mkdir(exist_ok=True)
        for item in corpus[kind]:
            (directory / f"{item['number']}.json").write_text(json.dumps(item, ensure_ascii=True))
    summary = {
        "repo": corpus["repo"],
        "counts": {kind: len(corpus[kind]) for kind in ("issues", "reports", "managed", "excluded")},
        "issues": [compact(item) for item in corpus["issues"]],
        "reports": [
            {
                **compact(item),
                "deep_report": "<!-- gh-aw-workflow-id: deep-report -->" in (item.get("body") or ""),
                "references": sorted(set(int(n) for n in re.findall(
                    r"(?<![a-zA-Z0-9])#([0-9]+)\b", item.get("body") or "",
                ))),
            }
            for item in corpus["reports"]
        ],
        "managed": [
            {"number": item["number"], "assigned": bool(item.get("assignees")),
             "cluster": metadata(item)}
            for item in corpus["managed"]
        ],
        "excluded": corpus["excluded"], "seeds": seed_clusters(corpus["issues"]),
    }
    (output / "index.json").write_text(json.dumps(summary, indent=2, ensure_ascii=True))
    print(json.dumps(summary["counts"]))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repo):
        parser.error("--repo must be owner/name")
    cutoff = run_cutoff(args.repo)
    issues = collect_issues(args.repo, cutoff)
    sources = [item for item in issues if aw_authored(item, args.repo) and not managed(item)]
    discussions = collect_discussions(args.repo, sources)
    write_evidence(build_corpus(args.repo, issues, discussions, cutoff), args.output)


if __name__ == "__main__":
    main()
