const fs = require("node:fs");
const path = require("node:path");
const { parseArgs } = require("node:util");

const repoId = "aw-issue-clustering";
const prefix = "[AW Top 10] ";
const label = "aw-essential";
const ownerMarker = `<!-- gh-aw-workflow-id: ${repoId} -->`;
const start = "<!-- aw-essential-start -->";
const end = "<!-- aw-essential-end -->";
const meta = /<!-- aw-essential-meta: (.+) -->/;
const escapeRegex = value => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

function requireValid(condition, message) {
  if (!condition) throw new Error(message);
}

function text(value, field, limit = 4000, min = 10) {
  requireValid(typeof value === "string" && value.trim().length >= min && value.length <= limit, `Invalid ${field}`);
  requireValid(!value.includes("<!--") && !/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(value), `Control characters or metadata injection in ${field}`);
}

function authored(item, repo) {
  const author = item.user || item.author || {};
  const body = item.body || "";
  const run = new RegExp(`https://github\\.com/${escapeRegex(repo)}/actions/runs/[0-9]+\\b`);
  return (author.type || author.__typename) === "Bot" && (/<!-- gh-aw-(?:agentic-workflow|workflow-id|group):/.test(body) || (run.test(body) && /^> (?:AI generated by|Generated (?:by|from)) \[/m.test(body)));
}

function owns(item) {
  return (item.user?.type || item.author?.__typename) === "Bot" && (item.body || "").includes(ownerMarker) && (item.title || "").startsWith(prefix);
}

function managed(item) {
  return owns(item) && item.body.includes(start) && item.body.includes(end) && meta.test(item.body);
}

function metadata(item) {
  return JSON.parse(meta.exec(item.body)[1]);
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map(key => [key, canonical(value[key])])
    );
  }
  return value;
}

function buildCorpus(repo, issues, discussions, cutoff) {
  const completed = issues.filter(item => managed(item) && item.state === "closed" && item.state_reason === "completed");
  const resolved = new Map();
  for (const item of completed) {
    for (const number of metadata(item).members) {
      if ((resolved.get(number)?.closed_at || "") < item.closed_at) resolved.set(number, item);
    }
  }
  const activeAssigned = new Set(issues.filter(item => managed(item) && item.state === "open" && item.assignees?.length).flatMap(item => metadata(item).members));
  const corpus = { repo, cutoff, completed, cleanup: [], issues: [], reports: [], managed: [], excluded: [], recently_closed: [] };
  for (const item of [...issues].sort((a, b) => a.number - b.number)) {
    const body = item.body || "";
    if (item.state !== "open") continue;
    requireValid(!owns(item) || managed(item), `Owned summary #${item.number} has malformed metadata; refusing queue changes`);
    if (managed(item)) corpus.managed.push(item);
    else if (cutoff && item.created_at > cutoff) corpus.excluded.push({ number: item.number, reason: "Arrived after run start; next daily pass" });
    else if (!authored(item, repo)) corpus.excluded.push({ number: item.number, reason: "No bot + AW provenance" });
    else if (body.includes(ownerMarker)) corpus.excluded.push({ number: item.number, reason: "Clustering workflow output" });
    else if (resolved.has(item.number) && item.updated_at <= resolved.get(item.number).closed_at) {
      corpus.excluded.push({ number: item.number, reason: "Operator completed its cluster; no newer evidence" });
      if (!activeAssigned.has(item.number) && !item.title.startsWith("[WIP] ") && !body.includes("<!-- gh-aw-group:")) {
        const summary = resolved.get(item.number);
        corpus.cleanup.push({ number: item.number, summary_number: summary.number, summary_closed_at: summary.closed_at, source_updated_at: item.updated_at });
      }
    } else if (item.title.startsWith("[WIP] ") || body.includes("<!-- gh-aw-group:")) corpus.excluded.push({ number: item.number, reason: "WIP or grouping container" });
    else corpus.issues.push(item);
  }
  corpus.reports = discussions.filter(item => authored(item, repo) && !(item.body || "").includes(ownerMarker));
  corpus.recently_closed = issues
    .filter(
      item =>
        cutoff &&
        item.state === "closed" &&
        item.closed_at >= cutoff &&
        item.created_at <= cutoff &&
        authored(item, repo) &&
        !(item.body || "").includes(ownerMarker) &&
        !item.title.startsWith("[WIP] ") &&
        !(item.body || "").includes("<!-- gh-aw-group:")
    )
    .map(item => item.number);
  return corpus;
}

async function collectIssues(github, owner, repo, cutoff) {
  const list = async params => github.paginate(github.rest.issues.listForRepo, { owner, repo, per_page: 100, ...params });
  const [open, closed, recent] = await Promise.all([list({ state: "open" }), list({ state: "closed", labels: label }), cutoff ? list({ state: "closed", since: cutoff }) : []]);
  return [...new Map([...open, ...closed, ...recent].filter(item => !item.pull_request).map(item => [item.number, item])).values()];
}

const discussionFields = "number title body url createdAt updatedAt closed author { login __typename } category { id name }";

async function collectDiscussions(github, owner, repo, issues, core, now = Date.now()) {
  const cutoff = new Date(now - 14 * 86400000).toISOString().replace(/\.\d{3}Z$/, "Z");
  const found = new Map();
  let cursor = null;
  for (let page = 0; page < 100; page++) {
    const data = await github.graphql(
      `query($owner:String!, $name:String!, $cursor:String) {
      repository(owner:$owner, name:$name) {
        discussions(first:100, after:$cursor, orderBy:{field:UPDATED_AT, direction:DESC}) {
          pageInfo { hasNextPage endCursor } nodes { ${discussionFields} }
        }
      }
    }`,
      { owner, name: repo, cursor }
    );
    const connection = data.repository.discussions;
    for (const item of connection.nodes) {
      if (item.updatedAt >= cutoff && authored(item, `${owner}/${repo}`)) found.set(item.number, item);
    }
    if (!connection.pageInfo.hasNextPage || connection.nodes.some(item => item.updatedAt < cutoff)) break;
    requireValid(page < 99, "Discussion pagination exceeded 100 pages; refusing partial coverage");
    cursor = connection.pageInfo.endCursor;
  }
  const linked = new Set();
  for (const issue of issues) {
    for (const match of (issue.body || "").matchAll(new RegExp(`https://github\\.com/${escapeRegex(`${owner}/${repo}`)}/discussions/([0-9]+)\\b`, "g"))) linked.add(Number(match[1]));
  }
  for (const number of [...linked].sort((a, b) => a - b)) {
    if (found.has(number)) continue;
    let item;
    try {
      const data = await github.graphql(
        `query($owner:String!, $name:String!, $number:Int!) {
        repository(owner:$owner, name:$name) { discussion(number:$number) { ${discussionFields} } }
      }`,
        { owner, name: repo, number }
      );
      item = data.repository.discussion;
    } catch (error) {
      if (error.errors?.length && error.errors.every(entry => entry.type === "NOT_FOUND" && JSON.stringify(entry.path) === '["repository","discussion"]')) {
        core.info(`Linked discussion #${number} does not exist; excluded from evidence`);
        continue;
      }
      throw error;
    }
    if (item && authored(item, `${owner}/${repo}`)) found.set(number, item);
  }
  return [...found.values()].sort((a, b) => a.number - b.number);
}

function refreshClosed(plan, corpus, core = { info() {} }) {
  requireValid(plan && typeof plan === "object" && Array.isArray(plan.clusters), "Invalid clustering plan");
  requireValid(Array.isArray(plan.deferred), "Missing deferred coverage");
  const result = structuredClone(plan);
  const closed = new Set([...corpus.recently_closed, ...corpus.cleanup.map(item => item.number)]);
  const assigned = new Set(corpus.managed.filter(item => item.assignees?.length).map(item => metadata(item).key));
  for (const item of corpus.managed) {
    if (!item.assignees?.length || !corpus.cutoff || item.updated_at < corpus.cutoff) continue;
    const frozen = metadata(item);
    result.clusters = result.clusters.map(cluster => {
      if (cluster?.key !== frozen.key || JSON.stringify(canonical(cluster)) === JSON.stringify(canonical(frozen))) return cluster;
      core.info(`Reconciliation: summary #${item.number} was assigned or edited after run start; preserved its live frozen scope`);
      return structuredClone(frozen);
    });
  }
  const dropped = [];
  let removed = 0;
  result.clusters = result.clusters.filter(cluster => {
    requireValid(cluster && Array.isArray(cluster.members), "Invalid cluster members");
    if (assigned.has(cluster.key)) return true;
    requireValid(cluster.members.every(Number.isInteger), "Invalid source numbers");
    const original = cluster.members.length;
    cluster.members = cluster.members.filter(number => !closed.has(number));
    removed += original - cluster.members.length;
    if (original && !cluster.members.length) {
      dropped.push(cluster.key);
      return false;
    }
    return true;
  });
  requireValid(
    result.deferred.every(item => item && Number.isInteger(item.number)),
    "Invalid deferred entries"
  );
  result.deferred = result.deferred.filter(item => !closed.has(item.number));
  if (dropped.length)
    result.shortfall_reason = `${dropped.length} planned assignments lost all eligible sources during analysis. Sources were closed or resolved by completed summaries; expiry alone is not proof of a fix. The next daily pass reassesses the remaining backlog.`;
  if (removed) core.info(`Reconciliation: removed ${removed} verified AW sources closed or resolved by completed summaries; retired ${dropped.length} empty candidate assignments`);
  return result;
}

function validatePlan(plan, corpus) {
  requireValid(plan && typeof plan === "object", "Plan must be an object");
  const { clusters, deferred } = plan;
  requireValid(Array.isArray(clusters) && clusters.length <= 10, "At most ten clusters allowed");
  requireValid(Array.isArray(deferred), "Missing deferred coverage");
  const eligible = new Set(corpus.issues.map(item => item.number));
  const reports = new Set(corpus.reports.map(item => item.number));
  const existing = new Map(corpus.managed.map(item => [metadata(item).key, item]));
  requireValid(existing.size === corpus.managed.length, "Duplicate managed keys; reconcile manually");
  requireValid(existing.size <= 10, "More than ten owned summaries open; reconcile manually");
  const seen = new Set();
  const keys = new Set();
  for (const cluster of clusters) {
    requireValid(cluster && typeof cluster === "object", "Cluster must be an object");
    const key = cluster.key;
    requireValid(typeof key === "string" && /^[a-z][a-z0-9-]{2,63}$/.test(key), "Invalid cluster key");
    requireValid(!keys.has(key), "Duplicate cluster key");
    keys.add(key);
    const previous = existing.get(key);
    for (const field of ["title", "summary", "fix", "rationale"]) {
      text(cluster[field], field, field === "title" ? 120 : 4000);
      if (!previous?.assignees?.length) {
        if (field === "title") requireValid(cluster.title.trim().length < 60, "Title must be a complete phrase under 60 characters");
        else requireValid(/[.!?]$/.test(cluster[field].trim()), `${field} must end with sentence punctuation; do not clip prose`);
      }
    }
    requireValid(Array.isArray(cluster.acceptance) && cluster.acceptance.length >= 1 && cluster.acceptance.length <= 6, "Missing acceptance criteria");
    for (const criterion of cluster.acceptance) {
      text(criterion, "acceptance criterion", 1000);
      if (!previous?.assignees?.length) requireValid(/[.!?]$/.test(criterion.trim()), "Acceptance criterion must end with sentence punctuation; do not clip prose");
    }
    for (const field of ["impact", "confidence", "effort"]) {
      requireValid(Number.isInteger(cluster[field]) && cluster[field] >= 1 && cluster[field] <= 5, `Invalid ${field}`);
    }
    requireValid(Array.isArray(cluster.members) && cluster.members.length && cluster.members.every(Number.isInteger) && new Set(cluster.members).size === cluster.members.length, "Members must be unique issue numbers");
    let liveMembers;
    if (previous?.assignees?.length) {
      requireValid(JSON.stringify(canonical(cluster)) === JSON.stringify(canonical(metadata(previous))), `Assigned cluster ${key} must remain unchanged`);
      liveMembers = cluster.members.filter(number => eligible.has(number));
    } else {
      requireValid(
        cluster.members.every(number => eligible.has(number)),
        "Cluster includes human, closed, or unverified issues"
      );
      liveMembers = cluster.members;
      if (previous)
        requireValid(
          metadata(previous).members.some(number => liveMembers.includes(number)),
          `Cannot repurpose cluster identity ${key}`
        );
    }
    for (const number of liveMembers) {
      requireValid(!seen.has(number), "Issue appears in multiple clusters");
      seen.add(number);
    }
    requireValid(Array.isArray(cluster.reports) && cluster.reports.every(Number.isInteger) && new Set(cluster.reports).size === cluster.reports.length, "Reports must be unique discussion numbers");
    if (!previous?.assignees?.length)
      requireValid(
        cluster.reports.every(number => reports.has(number)),
        "Report lacks AW provenance or is outside the evidence window"
      );
  }
  for (const item of deferred) {
    requireValid(item && Number.isInteger(item.number) && eligible.has(item.number) && !seen.has(item.number), "Invalid deferred issue");
    text(item.reason, "deferral reason", 1000, 1);
    seen.add(item.number);
  }
  requireValid(seen.size === eligible.size, "Every eligible AW issue must be clustered or explicitly deferred");
  requireValid(
    corpus.managed.filter(item => item.assignees?.length).every(item => keys.has(metadata(item).key)),
    "Assigned clusters cannot be retired"
  );
  if (clusters.length < Math.min(10, eligible.size)) text(plan.shortfall_reason, "shortfall reason");
  return [...clusters].sort((a, b) => (b.impact * b.confidence * Math.log2(1 + b.members.length)) / b.effort - (a.impact * a.confidence * Math.log2(1 + a.members.length)) / a.effort || a.key.localeCompare(b.key));
}

function safeText(value) {
  return value
    .replace(/https?:\/\/\S+/g, "[URL omitted; use evidence links below]")
    .replace(/@/g, "@\u200b")
    .replace(/(?<!\w)\/(?=[a-zA-Z])/g, "/\u200b")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");
}

function island(cluster, rank, repo) {
  const links = cluster.members.map(number => `[#${number}](https://github.com/${repo}/issues/${number})`).join(" ");
  const reports = cluster.reports.map(number => `[discussion #${number}](https://github.com/${repo}/discussions/${number})`).join(" ") || "No corroborating AW discussion; evidence comes from the source issues.";
  const criteria = cluster.acceptance.map(value => `- [ ] ${safeText(value)}`).join("\n");
  return `${start}
**Priority ${rank}/10** | **${cluster.members.length} source issues** | Impact ${cluster.impact}/5 | Confidence ${cluster.confidence}/5 | Effort ${cluster.effort}/5

### One assignment, one coherent fix
${safeText(cluster.summary)}

### Implementation scope
${safeText(cluster.fix)}

### Done when
${criteria}

### Why now
${safeText(cluster.rationale)}

<details><summary>AW source issues and corroborating reports</summary>

${links}

${reports}

</details>

Unchanged AW sources close only after this summary is completed. Newer source activity and not-planned retirement do not trigger source closure. Assigned summaries are frozen; unassign to allow reclustering.

<!-- aw-essential-meta: ${JSON.stringify(canonical(cluster))} -->
${end}`;
}

function replaceIsland(body, replacement) {
  requireValid(body.split(start).length === 2 && body.split(end).length === 2, "Malformed managed island");
  return body.slice(0, body.indexOf(start)) + replacement + body.slice(body.indexOf(end) + end.length);
}

async function ensureLabel(github, owner, repo, staged, core) {
  const labels = await github.paginate(github.rest.issues.listLabelsForRepo, { owner, repo, per_page: 100 });
  if (labels.some(item => item.name === label)) return;
  if (staged) core.info(`Preview: create label ${label}`);
  else await github.rest.issues.createLabel({ owner, repo, name: label, color: "1D76DB", description: "Essential AW-generated issue clusters: assign one to resolve related findings" });
}

async function reconcile(github, owner, repo, clusters, corpus, staged, core, createIssue) {
  const existing = new Map(corpus.managed.map(item => [metadata(item).key, item]));
  const wanted = new Set(clusters.map(cluster => cluster.key));
  const retiring = [...existing].filter(([key]) => !wanted.has(key)).map(([, item]) => item);
  requireValid(corpus.managed.length <= 10, "More than ten managed issues already open");
  requireValid(
    retiring.every(item => !item.assignees?.length),
    "Cannot close assigned work"
  );
  const liveIssue = async number => (await github.rest.issues.get({ owner, repo, issue_number: number })).data;
  for (const item of retiring) {
    if (!staged) {
      const live = await liveIssue(item.number);
      requireValid(managed(live) && !live.assignees?.length, "Ownership or assignment changed; rerun");
      requireValid(live.updated_at === item.updated_at, "Managed issue changed during reconciliation");
      await github.rest.issues.update({ owner, repo, issue_number: item.number, state: "closed", state_reason: "not_planned" });
    }
    core.info(`${staged ? "Preview: " : ""}retire summary #${item.number} (sources untouched)`);
  }
  const result = [];
  for (const [index, cluster] of clusters.entries()) {
    const rank = index + 1;
    let item = existing.get(cluster.key);
    const title = prefix + String(rank).padStart(2, "0") + " " + cluster.title;
    const content = island(cluster, rank, `${owner}/${repo}`);
    let url;
    if (item) {
      if (!staged) {
        const live = await liveIssue(item.number);
        requireValid(managed(live), "Summary ownership changed; refusing mutation");
        requireValid(live.updated_at === item.updated_at, "Summary edited or assigned; rerun");
        if (!live.labels.some(value => value.name === label)) {
          await github.rest.issues.addLabels({ owner, repo, issue_number: item.number, labels: [label] });
          item = await liveIssue(item.number);
          requireValid(managed(item), "Summary ownership changed; refusing mutation");
        }
      }
      url = item.html_url;
      if (item.assignees?.length) {
        result.push([rank, cluster, url]);
        continue;
      }
      const body = replaceIsland(item.body, content);
      if (!staged && (body !== item.body || title !== item.title)) {
        const live = await liveIssue(item.number);
        requireValid(managed(live) && !live.assignees?.length, "Ownership or assignment changed; rerun");
        requireValid(live.updated_at === item.updated_at, "Managed issue edited; rerun to preserve changes");
        await github.rest.issues.update({ owner, repo, issue_number: item.number, title, body });
      }
    } else if (!staged) {
      const live = await collectIssues(github, owner, repo);
      requireValid(live.filter(issue => issue.state === "open" && managed(issue)).length < 10, "Active queue is full; refusing an eleventh issue");
      requireValid(typeof createIssue === "function", "Attributed issue-creation API is required");
      const created = await createIssue({ owner, repo, title, body: content, labels: [label, "automation", "agentic-workflows", "cookie"] });
      requireValid(!created.staged, "Issue creation was unexpectedly staged during live reconciliation");
      url = created.issue.html_url;
    }
    result.push([rank, cluster, url]);
    core.info(`${staged ? "Preview: " : ""}${title}: ${url || ""}`);
  }
  return result;
}

async function cleanupCompleted(github, owner, repo, corpus, staged, core) {
  const summaries = new Map(corpus.completed.map(item => [item.number, item]));
  const cleaned = [];
  for (const candidate of corpus.cleanup) {
    const summary = (await github.rest.issues.get({ owner, repo, issue_number: candidate.summary_number })).data;
    const previous = summaries.get(candidate.summary_number);
    if (
      !managed(summary) ||
      summary.state !== "closed" ||
      summary.state_reason !== "completed" ||
      summary.closed_at !== candidate.summary_closed_at ||
      JSON.stringify(canonical(metadata(summary))) !== JSON.stringify(canonical(metadata(previous)))
    ) {
      core.info(`Cleanup: summary #${candidate.summary_number} was reopened or changed; kept source #${candidate.number} open`);
      continue;
    }
    const source = (await github.rest.issues.get({ owner, repo, issue_number: candidate.number })).data;
    if (source.state === "closed") continue;
    if (
      source.pull_request ||
      !authored(source, `${owner}/${repo}`) ||
      (source.body || "").includes(ownerMarker) ||
      source.title.startsWith("[WIP] ") ||
      (source.body || "").includes("<!-- gh-aw-group:") ||
      source.updated_at !== candidate.source_updated_at ||
      source.updated_at > summary.closed_at
    ) {
      core.info(`Cleanup: source #${candidate.number} has newer activity or changed provenance; kept it open`);
      continue;
    }
    if (!staged) await github.rest.issues.update({ owner, repo, issue_number: candidate.number, state: "closed", state_reason: "completed" });
    core.info(`${staged ? "Preview: " : ""}close AW source #${candidate.number}: summary #${summary.number} completed`);
    cleaned.push(candidate);
  }
  return cleaned;
}

function dashboardBody(result, plan, corpus, runId, cleanup = [], staged = false) {
  const rows = [
    start,
    "### Essential AW fixes",
    "Assign one summary issue to address its linked source findings. Only provenance-verified AW-created issues are considered; human issues are excluded.",
    `Saved issue view: \`is:issue is:open label:${label}\`.`,
    "",
    "| Rank | Assignable fix | Sources | Impact / confidence / effort |",
    "| --- | --- | ---: | --- |",
  ];
  for (const [rank, cluster, url] of result) {
    const title = safeText(cluster.title).replace(/\|/g, "&#124;").replace(/\n/g, " ");
    rows.push(`| ${rank} | ${url ? `[${title}](${url})` : `${title} (new in live mode)`} | ${cluster.members.length} | ${cluster.impact} / ${cluster.confidence} / ${cluster.effort} |`);
  }
  rows.push(
    "",
    `Coverage: ${corpus.issues.length} AW issues, ${corpus.reports.length} AW discussions (including deep reports), ${corpus.excluded.length} excluded issues, ${plan.deferred.length} explicitly deferred findings.`,
    "",
    "Ranking = impact x confidence x log2(1 + source count) / effort. Corroboration is not independent proof; repeated reports do not increase source count.",
    "",
    "<details><summary>Deferred AW findings</summary>",
    ""
  );
  for (const item of plan.deferred) {
    rows.push(`- [#${item.number}](https://github.com/${corpus.repo}/issues/${item.number}): ${safeText(item.reason)}`);
  }
  if (plan.shortfall_reason) rows.push("", safeText(plan.shortfall_reason));
  if (cleanup.length) {
    rows.push("", `Cleanup: ${staged ? "would close" : "closed"} ${cleanup.length} unchanged AW sources linked to completed summaries.`);
    for (const item of cleanup) rows.push(`- [#${item.number}](https://github.com/${corpus.repo}/issues/${item.number}) resolved by [summary #${item.summary_number}](https://github.com/${corpus.repo}/issues/${item.summary_number}).`);
  }
  if (runId) rows.push("", `[Workflow run](https://github.com/${corpus.repo}/actions/runs/${runId})`);
  rows.push("", "</details>", "", end, "", ownerMarker);
  return rows.join("\n");
}

async function publishDashboard(github, owner, repo, body, staged, core) {
  requireValid(body.length <= 60000, "Dashboard exceeds GitHub body limit");
  if (staged) {
    core.info("Preview: update the AW Essential 10 discussion");
    return;
  }
  const data = await github.graphql(
    `query($searchTerm:String!) {
    search(query:$searchTerm, type:DISCUSSION, first:100) {
      pageInfo { hasNextPage }
      nodes { ... on Discussion { id title body closed author { __typename } } }
    }
  }`,
    { searchTerm: `repo:${owner}/${repo} in:title "AW Essential 10"` }
  );
  requireValid(!data.search.pageInfo.hasNextPage, "Dashboard search truncated");
  const dashboards = data.search.nodes.filter(item => item?.title === "AW Essential 10" && item.author?.__typename === "Bot" && item.body.includes(ownerMarker));
  requireValid(dashboards.length <= 1, "Multiple owned dashboards; reconcile manually");
  if (dashboards.length) {
    const current = dashboards[0];
    requireValid(!current.closed, "Operator closed dashboard; refusing to recreate it");
    const replacement = start + body.split(start)[1].split(end)[0] + end;
    const updated = replaceIsland(current.body, replacement);
    if (current.body !== updated) {
      try {
        await github.graphql(
          `mutation($id:ID!, $body:String!) {
          updateDiscussion(input:{discussionId:$id, body:$body}) { discussion { id } }
        }`,
          { id: current.id, body: updated }
        );
      } catch (error) {
        if (!String(error).includes("Resource not accessible by integration")) throw error;
        await github.graphql(
          `mutation($id:ID!, $body:String!) {
          addDiscussionComment(input:{discussionId:$id, body:$body}) { comment { id } }
        }`,
          { id: current.id, body }
        );
        core.info("Dashboard edit denied; published the current queue as a discussion comment");
      }
    }
  } else {
    const details = await github.graphql(
      `query($owner:String!, $name:String!) {
      repository(owner:$owner, name:$name) {
        id discussionCategories(first:100) { nodes { id name } pageInfo { hasNextPage } }
      }
    }`,
      { owner, name: repo }
    );
    requireValid(!details.repository.discussionCategories.pageInfo.hasNextPage, "Category discovery truncated");
    const category = details.repository.discussionCategories.nodes.find(item => item.name.toLowerCase() === "audits");
    requireValid(category, "Repository needs an audits discussion category");
    await github.graphql(
      `mutation($repo:ID!, $category:ID!, $body:String!) {
      createDiscussion(input:{repositoryId:$repo, categoryId:$category, title:"AW Essential 10", body:$body}) { discussion { id } }
    }`,
      { repo: details.repository.id, category: category.id, body }
    );
  }
}

async function publish({ github, context, core, createIssue }) {
  const { owner, repo } = context.repo;
  const output = JSON.parse(fs.readFileSync(process.env.GH_AW_AGENT_OUTPUT, "utf8"));
  const items = (output.items || []).filter(item => item.type === "publish_essential_issues");
  requireValid(items.length === 1, "Exactly one publish_essential_issues plan required");
  requireValid(items[0].plan_path === "agent/aw-issue-clustering/plan.json", "Invalid clustering plan artifact path");
  const planFile = path.join(path.dirname(process.env.GH_AW_AGENT_OUTPUT), items[0].plan_path);
  let planText;
  const fd = fs.openSync(planFile, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
  try {
    const stat = fs.fstatSync(fd);
    requireValid(stat.isFile() && stat.size <= 1048576, "Plan artifact must be a regular JSON file no larger than 1 MiB");
    planText = fs.readFileSync(fd, "utf8");
  } finally {
    fs.closeSync(fd);
  }
  const plan = JSON.parse(planText);
  const cutoff = (await github.rest.actions.getWorkflowRun({ owner, repo, run_id: context.runId })).data.created_at;
  const issues = await collectIssues(github, owner, repo, cutoff);
  const sources = buildCorpus(`${owner}/${repo}`, issues, [], cutoff).issues;
  const discussions = await collectDiscussions(github, owner, repo, sources, core);
  const corpus = buildCorpus(`${owner}/${repo}`, issues, discussions, cutoff);
  const refreshed = refreshClosed(plan, corpus, core);
  const clusters = validatePlan(refreshed, corpus);
  const staged = process.env.GH_AW_SAFE_OUTPUTS_STAGED === "true";
  requireValid(
    clusters.every((cluster, index) => island(cluster, index + 1, corpus.repo).length < 60000),
    "Issue body too large"
  );
  const preview = clusters.map((cluster, index) => [index + 1, cluster, `https://github.com/${corpus.repo}/issues/999999999`]);
  requireValid(dashboardBody(preview, refreshed, corpus, context.runId, corpus.cleanup, staged).length < 60000, "Dashboard body too large");
  const cleanup = await cleanupCompleted(github, owner, repo, corpus, staged, core);
  await ensureLabel(github, owner, repo, staged, core);
  const result = await reconcile(github, owner, repo, clusters, corpus, staged, core, createIssue);
  const body = dashboardBody(result, refreshed, corpus, context.runId, cleanup, staged);
  await publishDashboard(github, owner, repo, body, staged, core);
  await core.summary.addRaw(body).write();
}

function validateFile(args = process.argv.slice(2)) {
  const { values } = parseArgs({ args, options: { repo: { type: "string" }, corpus: { type: "string" }, plan: { type: "string" } } });
  requireValid(values.repo && values.corpus && values.plan, "--repo, --corpus and --plan are required");
  const corpus = JSON.parse(fs.readFileSync(values.corpus, "utf8"));
  const plan = JSON.parse(fs.readFileSync(values.plan, "utf8"));
  requireValid(corpus.repo === values.repo, "Corpus repository mismatch");
  const clusters = validatePlan(plan, corpus);
  return `Validated ${clusters.length} clusters; complete coverage of ${corpus.issues.length} AW issues`;
}

if (require.main === module) {
  try {
    process.stdout.write(validateFile() + "\n");
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  }
}

module.exports = { publish, buildCorpus, refreshClosed, validatePlan, validateFile, island, reconcile, cleanupCompleted, dashboardBody, publishDashboard, collectDiscussions, collectIssues, metadata };
