#!/usr/bin/env python3
"""Offline tests for provenance, clustering, queue bounds and ownership guards."""

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import aw_issue_clustering as collect
import aw_issue_clustering_publish as publish


REPO = "github/gh-aw"


def issue(number, title="Repair shared ledger persistence", body=None, **overrides):
    result = {
        "number": number, "title": title,
        "body": body if body is not None else (
            "Ledger projections are missing after a successful append.\n"
            "<!-- gh-aw-agentic-workflow: Smoke Ledgers -->"
        ),
        "user": {"type": "Bot", "login": "github-actions[bot]"},
        "state": "open", "assignees": [], "labels": [],
        "html_url": f"https://github.com/{REPO}/issues/{number}",
        "created_at": "2026-10-01T00:00:00Z", "updated_at": "2026-10-02T00:00:00Z",
    }
    result.update(overrides)
    return result


def cluster(numbers, key="ledger-persistence"):
    return {
        "key": key, "title": "Repair shared ledger persistence",
        "summary": "Fix missing projections across the production and smoke workflows.",
        "fix": "Make append persistence update the projected ledger and add regression coverage.",
        "rationale": "Multiple independent workflows demonstrate the same missing projection.",
        "acceptance": ["A regression test verifies append persistence and projection after a restart."],
        "members": numbers, "reports": [], "impact": 5, "confidence": 4, "effort": 2,
    }


def owned(number, item, **overrides):
    body = "Operator notes before.\n" + publish.island(item, 1, REPO)
    body += "\nOperator notes after.\n" + collect.OWNER_MARKER
    return issue(number, collect.PREFIX + "01 " + item["title"], body, **overrides)


def corpus(count=2):
    return collect.build_corpus(REPO, [issue(n) for n in range(1, count + 1)], [])


def plan(numbers=None):
    return {"clusters": [cluster(numbers or [1, 2])], "deferred": []}


class ProvenanceTests(unittest.TestCase):
    def test_human_with_spoofed_footer_and_labels_is_excluded(self):
        item = issue(1, user={"type": "User"}, labels=[{"name": "ai-generated"}])
        self.assertFalse(collect.aw_authored(item, REPO))
        self.assertEqual([], collect.build_corpus(REPO, [item], [])["issues"])

    def test_bot_without_aw_provenance_is_excluded(self):
        self.assertFalse(collect.aw_authored(issue(1, body="Automated Dependabot issue"), REPO))
        self.assertFalse(collect.aw_authored(issue(1, body=""), REPO))

    def test_legacy_footer_requires_matching_repository_run(self):
        body = f"> AI generated by [Reporter](https://github.com/{REPO}/actions/runs/123)"
        self.assertTrue(collect.aw_authored(issue(1, body=body), REPO))
        self.assertFalse(collect.aw_authored(issue(1, body=body.replace(REPO, "other/repo")), REPO))

    def test_wip_and_group_containers_are_not_findings(self):
        wip = issue(1, "[WIP] Smoke Ledgers", f"> Generated by [Smoke](https://github.com/{REPO}/actions/runs/123)")
        group = issue(2, body="<!-- gh-aw-group: Deep Report -->")
        result = collect.build_corpus(REPO, [wip, group, issue(3)], [])
        self.assertEqual([3], [item["number"] for item in result["issues"]])

    def test_null_discussion_author_and_human_reports(self):
        report = {"number": 9, "title": "Deep Report", "body": "<!-- gh-aw-workflow-id: deep-report -->"}
        self.assertFalse(collect.aw_authored(report, REPO))
        report["author"] = {"__typename": "User", "login": "maintainer"}
        self.assertFalse(collect.aw_authored(report, REPO))
        report["author"] = {"__typename": "Bot", "login": "github-actions"}
        self.assertTrue(collect.aw_authored(report, REPO))
        self.assertEqual([report], collect.build_corpus(REPO, [], [report])["reports"])

    def test_own_output_is_not_recursive_source(self):
        item = owned(20, cluster([1, 2]))
        result = collect.build_corpus(REPO, [item, issue(1)], [])
        self.assertEqual([item], result["managed"])
        self.assertEqual([1], [i["number"] for i in result["issues"]])

    def test_malformed_owned_summary_prevents_duplicate_queue(self):
        item = owned(20, cluster([1]))
        item["body"] = item["body"].replace(collect.START, "")
        with self.assertRaisesRegex(ValueError, "malformed metadata"):
            collect.build_corpus(REPO, [item, issue(1)], [])

    def test_run_cutoff_defers_new_arrivals_without_cutting_existing_queue(self):
        item = issue(1, created_at="2026-10-03T10:00:01Z")
        summary = owned(20, cluster([2]), created_at="2026-10-03T10:00:02Z")
        result = collect.build_corpus(REPO, [item, issue(2), summary], [], "2026-10-03T10:00:00Z")
        self.assertEqual([2], [i["number"] for i in result["issues"]])
        self.assertEqual([summary], result["managed"])

    def test_only_verified_mid_run_closures_are_refreshable(self):
        closed = issue(2, state="closed", closed_at="2026-10-03T01:00:00Z")
        human = issue(3, state="closed", closed_at="2026-10-03T01:00:00Z", user={"type": "User"})
        old = issue(4, state="closed", closed_at="2026-10-02T01:00:00Z")
        data = collect.build_corpus(REPO, [issue(1), closed, human, old], [], "2026-10-03T00:00:00Z")
        self.assertEqual([2], data["recently_closed"])
        value = publish.refresh_closed_sources(plan(), data)
        self.assertEqual([1], value["clusters"][0]["members"])
        self.assertEqual([cluster([1])], publish.validate_plan(value, data))
        invalid = publish.refresh_closed_sources(plan([1, 3]), data)
        with self.assertRaisesRegex(ValueError, "unverified"):
            publish.validate_plan(invalid, data)

    def test_completed_summaries_do_not_resurface_without_new_evidence(self):
        summary = owned(20, cluster([1, 2]), state="closed", state_reason="completed",
                        closed_at="2026-10-03T00:00:00Z")
        result = collect.build_corpus(REPO, [issue(1), issue(2), summary], [])
        self.assertEqual([], result["issues"])
        fresh = issue(2, updated_at="2026-10-04T00:00:00Z")
        result = collect.build_corpus(REPO, [issue(1), fresh, summary], [])
        self.assertEqual([2], [i["number"] for i in result["issues"]])
        summary["state_reason"] = "not_planned"
        self.assertEqual(2, len(collect.build_corpus(REPO, [issue(1), fresh, summary], [])["issues"]))

    @patch.object(collect, "gh_json")
    def test_issue_pagination_excludes_pull_requests(self, api):
        api.side_effect = [[[issue(1)], [issue(2), {**issue(3), "pull_request": {}}]], []]
        self.assertEqual([1, 2], [i["number"] for i in collect.collect_issues(REPO)])
        self.assertIn("--paginate", api.call_args_list[0].args)

    @patch.object(collect, "graphql")
    def test_report_pagination_and_linked_old_deep_report(self, api):
        def report(number, date):
            return {
                "number": number, "title": "DeepReport", "updatedAt": date,
                "author": {"__typename": "Bot"},
                "body": "<!-- gh-aw-workflow-id: deep-report -->",
            }
        api.side_effect = [
            {"repository": {"discussions": {
                "nodes": [report(10, "2026-10-02T00:00:00Z")],
                "pageInfo": {"hasNextPage": True, "endCursor": "page2"},
            }}},
            {"repository": {"discussions": {
                "nodes": [report(11, "2026-09-01T00:00:00Z")],
                "pageInfo": {"hasNextPage": True, "endCursor": "page3"},
            }}},
            {"repository": {"discussion": report(12, "2026-08-01T00:00:00Z")}},
        ]
        source = issue(1, body=f"https://github.com/{REPO}/discussions/12")
        result = collect.collect_discussions(REPO, [source], now=datetime(2026, 10, 3, tzinfo=timezone.utc))
        self.assertEqual([10, 12], [r["number"] for r in result])
        self.assertEqual("page2", api.call_args_list[1].kwargs["cursor"])

    @patch.object(collect, "graphql")
    def test_deleted_linked_report_warns_but_other_api_errors_fail(self, api):
        page = {"repository": {"discussions": {
            "nodes": [], "pageInfo": {"hasNextPage": False, "endCursor": None},
        }}}
        source = issue(1, body=f"https://github.com/{REPO}/discussions/12")
        missing = collect.GitHubAPIError("missing", [
            {"type": "NOT_FOUND", "path": ["repository", "discussion"]},
        ])
        api.side_effect = [page, missing]
        self.assertEqual([], collect.collect_discussions(REPO, [source]))
        api.side_effect = [page, collect.GitHubAPIError("permission denied", [])]
        with self.assertRaisesRegex(collect.GitHubAPIError, "permission denied"):
            collect.collect_discussions(REPO, [source])


class ClusteringTests(unittest.TestCase):
    def test_deterministic_complete_partition_for_450_issues(self):
        issues = [issue(n, f"Repair ledger projection partition {n % 15}") for n in range(1, 451)]
        first = collect.seed_clusters(issues)
        self.assertEqual(first, collect.seed_clusters(list(reversed(issues))))
        self.assertEqual(30, len(first))
        self.assertEqual(list(range(1, 451)), sorted(n for group in first for n in group["members"]))

    def test_empty_and_identical_documents(self):
        self.assertEqual([], collect.seed_clusters([]))
        self.assertEqual(3, len(collect.seed_clusters([issue(1), issue(2), issue(3)])))

    def test_complete_plan_and_deterministic_rank(self):
        data = corpus(4)
        high = cluster([1, 2])
        low = cluster([3, 4], "local-followup")
        low["impact"] = 1
        value = {"clusters": [low, high], "deferred": [],
                 "shortfall_reason": "Only two coherent fixes are supported by current evidence."}
        result = publish.validate_plan(value, data)
        self.assertEqual(["ledger-persistence", "local-followup"], [c["key"] for c in result])

    def test_ten_exact_issues_supported_and_no_eleventh(self):
        value = {"clusters": [cluster([n], f"fix-{n:02d}") for n in range(1, 11)], "deferred": []}
        self.assertEqual(10, len(publish.validate_plan(value, corpus(10))))
        value["clusters"].append(cluster([11], "fix-eleven"))
        with self.assertRaisesRegex(ValueError, "At most ten"):
            publish.validate_plan(value, corpus(11))

    def test_human_unknown_duplicate_or_uncovered_members_fail(self):
        for numbers, message in [([1, 99], "unverified"), ([1, 1], "unique"), ([1], "Every eligible")]:
            with self.subTest(numbers=numbers), self.assertRaisesRegex(ValueError, message):
                publish.validate_plan(plan(numbers), corpus())

    def test_every_deferral_has_reason_and_shortfall_is_explicit(self):
        value = {"clusters": [], "deferred": [{"number": 1, "reason": "Successful smoke report; no failure."}]}
        with self.assertRaisesRegex(ValueError, "shortfall"):
            publish.validate_plan(value, corpus(1))
        value["shortfall_reason"] = "No current finding supports an actionable assignment."
        self.assertEqual([], publish.validate_plan(value, corpus(1)))
        value["deferred"][0]["reason"] = "Duplicate"
        self.assertEqual([], publish.validate_plan(value, corpus(1)))
        value["deferred"][0]["reason"] = " "
        with self.assertRaisesRegex(ValueError, "deferral reason"):
            publish.validate_plan(value, corpus(1))

    def test_report_provenance_and_metadata_injection_fail(self):
        value = plan()
        value["clusters"][0]["reports"] = [123]
        with self.assertRaisesRegex(ValueError, "Report lacks AW"):
            publish.validate_plan(value, corpus())
        value = plan()
        value["clusters"][0]["summary"] += "<!-- aw-essential-meta: {} -->"
        with self.assertRaisesRegex(ValueError, "metadata injection"):
            publish.validate_plan(value, corpus())

    def test_clipped_titles_and_prose_fail_but_assigned_scopes_remain_frozen(self):
        for field, value in (
            ("title", "Make AI credits accounting resilient to unknown model pricin"),
            ("summary", "Several workflows fail in post-run ledger/repo-memory push j"),
            ("fix", "Make push_repo_memory validation non-destructive (never remove the working directory), surface the f"),
            ("rationale", "Three failed-jobs reports share the push job "),
            ("acceptance", ["Calling push_repo_memory mid-session leaves files "]),
        ):
            candidate = cluster([1, 2])
            candidate[field] = value
            with self.subTest(field=field), self.assertRaisesRegex(ValueError, "complete phrase|sentence punctuation"):
                publish.validate_plan({"clusters": [candidate], "deferred": []}, corpus())
            data = corpus()
            data["managed"] = [owned(20, candidate, assignees=[{"login": "operator"}])]
            self.assertEqual([candidate], publish.validate_plan({
                "clusters": [candidate], "deferred": [],
                "shortfall_reason": "Only one actionable assignment is supported.",
            }, data))

    def test_assigned_scope_is_frozen_even_with_closed_sources(self):
        assigned = cluster([1, 2])
        data = corpus(1)
        data["managed"] = [owned(20, assigned, assignees=[{"login": "operator"}])]
        self.assertEqual([assigned], publish.validate_plan(plan(), data))
        data["recently_closed"] = [2]
        self.assertEqual([assigned], publish.refresh_closed_sources(plan(), data)["clusters"])
        changed = plan()
        changed["clusters"][0]["fix"] = "Replace the assigned work with unrelated implementation."
        with self.assertRaisesRegex(ValueError, "unchanged"):
            publish.validate_plan(changed, data)
        with self.assertRaisesRegex(ValueError, "Assigned clusters"):
            publish.validate_plan({"clusters": [], "deferred": [{"number": 1, "reason": "Deferred pending evidence."}]}, data)

    def test_clipped_text_marked_with_ascii_ellipses_is_preserved(self):
        candidate = cluster([1, 2])
        candidate.update({
            "title": "Make AI credits accounting resilient to unknown models...",
            "summary": "The accounting guardrail rejects unknown models...",
            "fix": "Provide a pricing fallback and validate the ledger...",
            "rationale": "Related workflows report the same accounting failure...",
            "acceptance": ["Unknown-model runs use a fallback price with a warning..."],
        })
        value = {
            "clusters": [candidate], "deferred": [],
            "shortfall_reason": "Only one coherent assignment is supported.",
        }
        self.assertLess(len(candidate["title"]), 60)
        self.assertEqual([candidate], publish.validate_plan(value, corpus()))
        body = publish.island(candidate, 1, REPO)
        for text in (candidate["summary"], candidate["fix"], candidate["rationale"], *candidate["acceptance"]):
            self.assertIn(text, body)

    def test_identity_cannot_be_repurposed(self):
        data = corpus(3)
        data["managed"] = [owned(20, cluster([1, 2]))]
        value = {"clusters": [cluster([3])], "deferred": [
            {"number": n, "reason": "Deferred pending current reproducible evidence."} for n in [1, 2]
        ]}
        with self.assertRaisesRegex(ValueError, "repurpose"):
            publish.validate_plan(value, data)


class PublishingTests(unittest.TestCase):
    @patch.object(publish, "gh_json")
    def test_unchanged_summary_is_idempotent(self, api):
        value = cluster([1, 2])
        item = owned(20, value, labels=[{"name": collect.CLUSTER_LABEL}])
        data = corpus()
        data["managed"] = [item]
        api.return_value = item
        publish.reconcile([value], data)
        self.assertEqual(1, api.call_count)
        self.assertNotIn("--method", api.call_args.args)

    @patch.object(publish, "gh_json")
    def test_assigned_summary_receives_label_without_changing_scope(self, api):
        value = cluster([1, 2])
        item = owned(20, value, assignees=[{"login": "operator"}], labels=[{"name": "cookie"}])
        labeled = {**item, "labels": item["labels"] + [{"name": collect.CLUSTER_LABEL}]}
        data = corpus()
        data["managed"] = [item]
        api.side_effect = [item, labeled["labels"], labeled]
        publish.reconcile([value], data)
        self.assertEqual(3, api.call_count)
        self.assertTrue(api.call_args_list[1].args[0].endswith("/20/labels"))
        self.assertEqual({"labels": [collect.CLUSTER_LABEL]}, api.call_args_list[1].kwargs["payload"])

    def test_island_preserves_operator_text_and_sanitizes_prose(self):
        value = cluster([1, 2])
        original = owned(20, value)["body"]
        value["summary"] = "Do not @mention /assign or visit https://evil.example/path <script>."
        body = publish.replace_island(original, publish.island(value, 2, REPO))
        self.assertTrue(body.startswith("Operator notes before."))
        self.assertTrue(body.endswith("Operator notes after.\n" + collect.OWNER_MARKER))
        self.assertNotIn("<script>", body.split("<!-- aw-essential-meta:")[0])
        self.assertIn("@\u200bmention", body)
        self.assertIn(f"https://github.com/{REPO}/issues/1", body)

    @patch.object(publish, "gh_json")
    def test_staged_reconciliation_makes_no_api_writes(self, api):
        data = corpus()
        data["managed"] = [owned(20, cluster([1], "old-summary"))]
        result = publish.reconcile([cluster([1, 2])], data, staged=True)
        api.assert_not_called()
        self.assertEqual(1, len(result))

    @patch.object(publish, "collect_issues")
    @patch.object(publish, "gh_json")
    def test_retire_before_create_and_label_new_cluster(self, api, listing):
        data = corpus()
        old = owned(20, cluster([1], "old-summary"))
        data["managed"] = [old]
        api.side_effect = [old, {"state": "closed"}, {"html_url": f"https://github.com/{REPO}/issues/21"}]
        listing.return_value = []
        result = publish.reconcile([cluster([1, 2])], data)
        self.assertEqual(1, len(result))
        self.assertEqual("closed", api.call_args_list[1].kwargs["payload"]["state"])
        self.assertIn(collect.CLUSTER_LABEL, api.call_args_list[2].kwargs["payload"]["labels"])

    @patch.object(publish, "gh_json")
    def test_assignment_race_aborts_before_write(self, api):
        data = corpus()
        old = owned(20, cluster([1, 2]))
        data["managed"] = [old]
        api.return_value = {**old, "assignees": [{"login": "operator"}], "updated_at": "2026-10-03T00:00:00Z"}
        with self.assertRaisesRegex(ValueError, "edited or assigned"):
            publish.reconcile([cluster([1, 2])], data)
        self.assertEqual(1, api.call_count)

    @patch.object(publish, "collect_issues")
    def test_live_cap_blocks_eleventh_issue(self, listing):
        listing.return_value = [owned(20 + n, cluster([n], f"old-{n}")) for n in range(1, 11)]
        with self.assertRaisesRegex(ValueError, "eleventh"):
            publish.reconcile([cluster([1, 2])], corpus())

    @patch.object(publish, "gh_json")
    def test_label_created_when_absent_and_not_replaced(self, api):
        api.side_effect = [[], {"name": collect.CLUSTER_LABEL}]
        publish.ensure_cluster_label(REPO)
        self.assertEqual(collect.CLUSTER_LABEL, api.call_args.kwargs["payload"]["name"])
        api.reset_mock()
        api.side_effect = None
        api.return_value = [[{"name": collect.CLUSTER_LABEL}]]
        publish.ensure_cluster_label(REPO)
        self.assertEqual(1, api.call_count)

    @patch.object(publish, "graphql")
    def test_dashboard_updates_only_owned_bot_discussion(self, api):
        old_body = "Operator note.\n" + collect.START + "\nOld table\n" + collect.END + collect.OWNER_MARKER
        api.side_effect = [
            {"search": {"pageInfo": {"hasNextPage": False}, "nodes": [
                {"id": "human", "title": "AW Essential 10", "body": collect.OWNER_MARKER,
                 "author": {"__typename": "User"}, "closed": False},
                {"id": "owned", "title": "AW Essential 10", "body": old_body,
                 "author": {"__typename": "Bot"}, "closed": False},
            ]}},
            {"updateDiscussion": {"discussion": {"id": "owned"}}},
        ]
        body = collect.START + "\nUpdated ranked queue\n" + collect.END + collect.OWNER_MARKER
        publish.publish_dashboard(REPO, body)
        self.assertEqual("owned", api.call_args.kwargs["id"])
        self.assertTrue(api.call_args.kwargs["body"].startswith("Operator note."))

    @patch.object(publish, "graphql")
    def test_dashboard_comments_when_existing_discussion_cannot_be_edited(self, api):
        old_body = collect.START + "\nOld table\n" + collect.END + collect.OWNER_MARKER
        api.side_effect = [
            {"search": {"pageInfo": {"hasNextPage": False}, "nodes": [
                {"id": "owned", "title": "AW Essential 10", "body": old_body,
                 "author": {"__typename": "Bot"}, "closed": False},
            ]}},
            collect.GitHubAPIError("GitHub API request failed: Resource not accessible by integration", []),
            {"addDiscussionComment": {"comment": {"id": "new"}}},
        ]
        body = collect.START + "\nUpdated ranked queue\n" + collect.END + collect.OWNER_MARKER
        publish.publish_dashboard(REPO, body)
        self.assertEqual(3, api.call_count)
        self.assertIn("Updated ranked queue", api.call_args.kwargs["body"])
        self.assertEqual("owned", api.call_args.kwargs["id"])
        self.assertIn("addDiscussionComment", api.call_args.args[0])

    @patch.object(publish, "graphql")
    def test_dashboard_does_not_hide_other_update_errors(self, api):
        api.side_effect = [
            {"search": {"pageInfo": {"hasNextPage": False}, "nodes": [
                {"id": "owned", "title": "AW Essential 10",
                 "body": collect.START + "\nOld table\n" + collect.END + collect.OWNER_MARKER,
                 "author": {"__typename": "Bot"}, "closed": False},
            ]}},
            collect.GitHubAPIError("GitHub API request failed: rate limit exceeded", []),
        ]
        with self.assertRaisesRegex(collect.GitHubAPIError, "rate limit exceeded"):
            publish.publish_dashboard(REPO, collect.START + "\nNew table\n" + collect.END)
        self.assertEqual(2, api.call_count)

    @patch.object(publish, "graphql")
    def test_dashboard_comment_failure_is_not_hidden(self, api):
        api.side_effect = [
            {"search": {"pageInfo": {"hasNextPage": False}, "nodes": [
                {"id": "owned", "title": "AW Essential 10",
                 "body": collect.START + "\nOld table\n" + collect.END + collect.OWNER_MARKER,
                 "author": {"__typename": "Bot"}, "closed": False},
            ]}},
            collect.GitHubAPIError("Resource not accessible by integration", []),
            collect.GitHubAPIError("comment failed", []),
        ]
        with self.assertRaisesRegex(collect.GitHubAPIError, "comment failed"):
            publish.publish_dashboard(REPO, collect.START + "\nNew table\n" + collect.END)

    @patch.object(publish, "run_cutoff", return_value="2026-10-03T00:00:00Z")
    @patch.object(publish, "collect_discussions", return_value=[])
    @patch.object(publish, "collect_issues")
    @patch.object(publish, "gh_json", return_value=[])
    def test_safe_output_end_to_end_450_findings_to_ten_staged_issues(self, api, listing, reports, cutoff):
        source_issues = [issue(number) for number in range(1, 451)]
        listing.return_value = source_issues + [
            issue(500, user={"type": "User"}),
            issue(501, body="A bot without AW provenance"),
        ]
        value = {
            "clusters": [
                cluster(list(range(start, start + 45)), f"coherent-fix-{index}")
                for index, start in enumerate(range(1, 451, 45), 1)
            ],
            "deferred": [],
        }
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "agent_output.json"
            output.write_text(json.dumps({
                "items": [{"type": "publish_essential_issues", "plan": json.dumps(value)}],
            }))
            with patch("sys.argv", [
                "publish", "--repo", REPO, "--agent-output", str(output),
            ]), patch.dict(os.environ, {"GH_AW_SAFE_OUTPUTS_STAGED": "true"}, clear=True):
                publish.main()
        listing.assert_called_once_with(REPO, "2026-10-03T00:00:00Z")
        self.assertEqual(450, len(reports.call_args.args[1]))
        # Staged mode only reads label inventory; all ten issue and discussion writes are skipped.
        self.assertEqual(1, api.call_count)
        self.assertNotIn("--method", api.call_args.args)


if __name__ == "__main__":
    unittest.main()
