const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { collect, seedClusters, writeEvidence, features } = require("./aw_issue_clustering.cjs");
const { buildCorpus, collectIssues, collectDiscussions, island } = require("./aw_issue_clustering_publish.cjs");

const repo = "github/gh-aw";
const cutoff = "2026-10-03T00:00:00Z";
const marker = "<!-- gh-aw-workflow-id: aw-issue-clustering -->";
const issue = (number, overrides = {}) => ({
  number,
  title: "Repair shared ledger persistence",
  body: "Ledger projections are missing after a successful append.\n<!-- gh-aw-agentic-workflow: Smoke Ledgers -->",
  user: { type: "Bot", login: "github-actions[bot]" },
  state: "open",
  assignees: [],
  labels: [],
  html_url: `https://github.com/${repo}/issues/${number}`,
  created_at: "2026-10-01T00:00:00Z",
  updated_at: "2026-10-02T00:00:00Z",
  ...overrides,
});
const owned = (number, overrides = {}) =>
  issue(number, {
    title: "[AW Top 10] 01 Repair shared ledger persistence",
    body: `${island({ key: "ledger-persistence", title: "Repair shared ledger persistence", summary: "Restore ledger projections.", fix: "Persist ledger projections.", acceptance: ["Projections survive restarts."], rationale: "Many workflows are affected.", members: [1, 2], reports: [], impact: 5, confidence: 4, effort: 2 }, 1, repo)}\n${marker}`,
    ...overrides,
  });
const report = (number, updatedAt = cutoff, overrides = {}) => ({
  number,
  title: "Deep Report",
  body: "<!-- gh-aw-workflow-id: deep-report -->",
  url: `https://github.com/${repo}/discussions/${number}`,
  author: { __typename: "Bot", login: "github-actions" },
  updatedAt,
  ...overrides,
});
const page = (nodes, hasNextPage = false, endCursor = null) => ({ repository: { discussions: { nodes, pageInfo: { hasNextPage, endCursor } } } });

test("human spoofed provenance, unverified bots, WIP and grouping containers are excluded", () => {
  const issues = [
    issue(1, { user: { type: "User" }, labels: [{ name: "ai-generated" }] }),
    issue(2, { body: "Dependabot issue" }),
    issue(3, { title: "[WIP] Smoke Ledgers" }),
    issue(4, { body: "<!-- gh-aw-group: Deep Report -->" }),
    issue(5),
  ];
  const data = buildCorpus(repo, issues, []);
  assert.deepEqual(
    data.issues.map(item => item.number),
    [5]
  );
  assert.equal(data.excluded.length, 4);
  assert.ok(data.excluded.every(item => item.reason));
});

test("legacy provenance requires a generated footer and matching repository run", () => {
  const body = `> AI generated by [Reporter](https://github.com/${repo}/actions/runs/123)`;
  const issues = [issue(1, { body }), issue(2, { body: body.replace(repo, "other/repo") }), issue(3, { body: `https://github.com/${repo}/actions/runs/123` })];
  assert.deepEqual(
    buildCorpus(repo, issues, []).issues.map(item => item.number),
    [1]
  );
});

test("null and human discussion authors are excluded while AW bots are included", () => {
  const reports = [report(1, cutoff, { author: null }), report(2, cutoff, { author: { __typename: "User" } }), report(3)];
  assert.deepEqual(
    buildCorpus(repo, [], reports).reports.map(item => item.number),
    [3]
  );
});

test("own output is durable state, not recursive evidence; malformed metadata fails", () => {
  const summary = owned(20);
  const data = buildCorpus(repo, [summary, issue(1)], []);
  assert.deepEqual(data.managed, [summary]);
  assert.deepEqual(
    data.issues.map(item => item.number),
    [1]
  );
  assert.throws(() => buildCorpus(repo, [{ ...summary, body: summary.body.replace("<!-- aw-essential-start -->", "") }], []), /malformed metadata/);
});

test("run cutoff defers new arrivals without excluding existing queue state", () => {
  const data = buildCorpus(repo, [issue(1, { created_at: "2026-10-03T10:00:01Z" }), issue(2), owned(20, { created_at: "2026-10-03T10:00:02Z" })], [], cutoff);
  assert.deepEqual(
    data.issues.map(item => item.number),
    [2]
  );
  assert.deepEqual(
    data.managed.map(item => item.number),
    [20]
  );
  assert.match(data.excluded[0].reason, /next daily pass/);
});

test("completed summaries suppress only unchanged evidence, not retirement or new activity", () => {
  const summary = owned(20, { state: "closed", state_reason: "completed", closed_at: cutoff });
  assert.equal(buildCorpus(repo, [issue(1), issue(2), summary], []).issues.length, 0);
  assert.deepEqual(
    buildCorpus(repo, [issue(1), issue(2, { updated_at: "2026-10-04T00:00:00Z" }), summary], []).issues.map(item => item.number),
    [2]
  );
  assert.equal(buildCorpus(repo, [issue(1), issue(2), { ...summary, state_reason: "not_planned" }], []).issues.length, 2);
});

test("only verified sources closed during analysis qualify for reconciliation", () => {
  const closed = { state: "closed", closed_at: "2026-10-03T01:00:00Z" };
  const data = buildCorpus(repo, [issue(1, closed), issue(2, { ...closed, user: { type: "User" } }), issue(3, { ...closed, closed_at: "2026-10-02T01:00:00Z" }), owned(20, closed)], [], cutoff);
  assert.deepEqual(data.recently_closed, [1]);
});

test("REST pagination combines all inventories, deduplicates and excludes pull requests", async () => {
  const calls = [];
  const github = {
    paginate: async (fn, params) => {
      calls.push(params);
      if (params.state === "open") return [issue(1), issue(2), issue(3, { pull_request: {} })];
      return [issue(4, { state: "closed" }), issue(2)];
    },
    rest: { issues: { listForRepo() {} } },
  };
  assert.deepEqual(
    (await collectIssues(github, "github", "gh-aw", cutoff)).map(item => item.number),
    [1, 2, 4]
  );
  assert.equal(calls.length, 3);
  assert.ok(calls.every(params => params.per_page === 100));
  assert.equal(calls[1].labels, "aw-essential");
  assert.equal(calls[2].since, cutoff);
});

test("discussion pagination includes recent closed reports and linked old briefings", async () => {
  const calls = [];
  const responses = [page([report(10, cutoff, { closed: true })], true, "page2"), page([report(11, "2026-09-01T00:00:00Z")], true, "page3"), { repository: { discussion: report(12, "2026-08-01T00:00:00Z") } }];
  const github = {
    graphql: async (document, variables) => {
      calls.push(variables);
      return responses.shift();
    },
  };
  const data = await collectDiscussions(github, "github", "gh-aw", [issue(1, { body: `https://github.com/${repo}/discussions/12` })], { info() {} }, Date.parse(cutoff));
  assert.deepEqual(
    data.map(item => item.number),
    [10, 12]
  );
  assert.equal(calls[1].cursor, "page2");
  assert.equal(calls.length, 3);
});

test("nonexistent linked discussions are reported; other API failures propagate", async () => {
  const warnings = [];
  const source = issue(1, { body: `https://github.com/${repo}/discussions/12` });
  const missing = Object.assign(new Error("missing"), { errors: [{ type: "NOT_FOUND", path: ["repository", "discussion"] }] });
  const github = {
    graphql: async document => {
      if (document.includes("discussion(number:")) throw missing;
      return page([]);
    },
  };
  assert.deepEqual(await collectDiscussions(github, "github", "gh-aw", [source], { info: message => warnings.push(message) }), []);
  assert.match(warnings[0], /#12.*excluded/);
  for (const error of [new Error("permission denied"), Object.assign(new Error("not found elsewhere"), { errors: [{ type: "NOT_FOUND", path: ["repository"] }] })]) {
    github.graphql = async document => {
      if (document.includes("discussion(number:")) throw error;
      return page([]);
    };
    await assert.rejects(collectDiscussions(github, "github", "gh-aw", [source], { info() {} }), error);
  }
});

test("exhausted discussion pagination fails instead of accepting partial evidence", async () => {
  const github = { graphql: async () => page([report(1)], true, "next") };
  await assert.rejects(collectDiscussions(github, "github", "gh-aw", [], { info() {} }, Date.parse(cutoff)), /pagination exceeded/);
});

test("TF-IDF seeds deterministically partition every one of 450 findings", () => {
  const issues = Array.from({ length: 450 }, (_, index) => issue(index + 1, { title: `Repair ledger projection partition ${index % 15}` }));
  const seeds = seedClusters(issues);
  assert.deepEqual(seeds, seedClusters([...issues].reverse()));
  assert.equal(seeds.length, 30);
  assert.deepEqual(
    seeds.flatMap(group => group.members).sort((a, b) => a - b),
    issues.map(item => item.number)
  );
});

test("empty and identical documents produce complete nonempty seeds", () => {
  assert.deepEqual(seedClusters([]), []);
  const seeds = seedClusters([issue(1), issue(2), issue(3)]);
  assert.equal(seeds.length, 3);
  assert.ok(seeds.every(group => group.members.length));
  assert.ok(!features(issue(1)).has("workflow"));
});

test("evidence output retains full bodies, compact report references and frozen metadata", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "aw-clustering-evidence-"));
  try {
    const data = buildCorpus(repo, [issue(1), owned(20, { assignees: [{ login: "operator" }] })], [report(30, cutoff, { body: "<!-- gh-aw-workflow-id: deep-report -->\n#21 #21 #12" })], cutoff);
    const index = writeEvidence(data, directory);
    assert.deepEqual(JSON.parse(fs.readFileSync(path.join(directory, "corpus.json"), "utf8")), data);
    assert.deepEqual(JSON.parse(fs.readFileSync(path.join(directory, "issues/1.json"), "utf8")), data.issues[0]);
    assert.equal(index.managed[0].assigned, true);
    assert.deepEqual(index.managed[0].cluster.members, [1, 2]);
    assert.deepEqual(index.reports[0].references, [12, 21]);
    assert.equal(index.reports[0].deep_report, true);
    assert.ok(fs.existsSync(path.join(directory, "reports/30.json")));
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

test("github-script collection uses injected credentials and trusted run cutoff without writes", async () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "aw-clustering-collect-"));
  const calls = [];
  const github = {
    rest: {
      actions: {
        getWorkflowRun: async params => {
          calls.push(params);
          return { data: { created_at: cutoff } };
        },
      },
      issues: { listForRepo() {} },
    },
    paginate: async (fn, params) => (params.state === "open" ? [issue(1), issue(2, { created_at: "2026-10-04T00:00:00Z" })] : []),
    graphql: async () => page([]),
  };
  try {
    const summary = await collect({ github, context: { repo: { owner: "github", repo: "gh-aw" }, runId: 123 }, core: { info() {} }, output: directory });
    assert.equal(summary.counts.issues, 1);
    assert.equal(summary.counts.excluded, 1);
    assert.equal(calls[0].run_id, 123);
    assert.ok(fs.existsSync(path.join(directory, "index.json")));
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});
