// @ts-check
import { describe, it, expect, beforeAll, afterEach, afterAll } from "vitest";
import { createRequire } from "module";
import path from "path";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const { assembleMarkdownBodyParts, ensureBlankLineAfterDetails } = require("./markdown_body_helpers.cjs");

describe("markdown_body_helpers", () => {
  let originalPromptsDir;

  beforeAll(() => {
    const promptsDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "../md");
    originalPromptsDir = process.env.GH_AW_PROMPTS_DIR;
    process.env.GH_AW_PROMPTS_DIR = promptsDir;
  });

  afterEach(() => {
    delete process.env.GH_AW_DETECTION_CONCLUSION;
    delete process.env.GH_AW_DETECTION_REASON;
  });

  afterAll(() => {
    if (originalPromptsDir === undefined) {
      delete process.env.GH_AW_PROMPTS_DIR;
      return;
    }
    process.env.GH_AW_PROMPTS_DIR = originalPromptsDir;
  });

  it("builds workflow-id fallback marker when footer is disabled", () => {
    const parts = assembleMarkdownBodyParts({
      includeFooter: false,
      workflowName: "Workflow",
      runUrl: "https://example.com/runs/1",
      workflowId: "test-workflow",
      markerWhenFooterDisabled: "workflow-id",
    });

    expect(parts.noFooterMarker).toBe("<!-- gh-aw-workflow-id: test-workflow -->");
    expect(parts.footer).toBe("");
  });

  it("builds XML fallback marker when footer is disabled", () => {
    const parts = assembleMarkdownBodyParts({
      includeFooter: false,
      workflowName: "Workflow",
      runUrl: "https://example.com/runs/2",
      markerWhenFooterDisabled: "xml",
    });

    expect(parts.noFooterMarker).toContain("gh-aw-agentic-workflow: Workflow");
    expect(parts.footer).toBe("");
  });

  it("includes caution once in detection warning mode while footer remains caution-free", () => {
    process.env.GH_AW_DETECTION_CONCLUSION = "warning";
    process.env.GH_AW_DETECTION_REASON = "threat_detected";

    const parts = assembleMarkdownBodyParts({
      includeFooter: true,
      workflowName: "Workflow",
      runUrl: "https://example.com/runs/3",
      workflowSource: "owner/repo/.github/workflows/test.yml@main",
      workflowSourceURL: "https://github.com/owner/repo/blob/main/.github/workflows/test.yml",
      historyUrl: "https://github.com/search?q=test",
    });

    expect(parts.detectionCaution).toContain("[!CAUTION]");
    expect(parts.footer).toContain("Generated by");
    expect(parts.footer).not.toContain("[!CAUTION]");
  });
});

describe("ensureBlankLineAfterDetails", () => {
  it("inserts a blank line after a closing details tag", () => {
    const result = ensureBlankLineAfterDetails("<details>\n<summary>Title</summary>\n\nBody\n\n</details>\nFollowing text");
    expect(result).toBe("<details>\n<summary>Title</summary>\n\nBody\n\n</details>\n\nFollowing text");
  });

  it("leaves content untouched when a blank line already follows", () => {
    const markdown = "<details>\n<summary>Title</summary>\n\nBody\n\n</details>\n\nFollowing text";
    expect(ensureBlankLineAfterDetails(markdown)).toBe(markdown);
  });

  it("handles consecutive details blocks", () => {
    const result = ensureBlankLineAfterDetails("<details>\n<summary>A</summary>\n\na\n</details>\n<details>\n<summary>B</summary>\n\nb\n</details>\nend");
    expect(result).toBe("<details>\n<summary>A</summary>\n\na\n</details>\n\n<details>\n<summary>B</summary>\n\nb\n</details>\n\nend");
  });

  it("does not modify closing tags inside fenced code blocks", () => {
    const markdown = "```html\n<details>\n</details>\ntext\n```\ntail";
    expect(ensureBlankLineAfterDetails(markdown)).toBe(markdown);
  });

  it("does not modify blockquoted details blocks", () => {
    const markdown = "> <details>\n> <summary>Details</summary>\n>\n> body\n> </details>\n> trailing";
    expect(ensureBlankLineAfterDetails(markdown)).toBe(markdown);
  });

  it("ignores closing tags that share a line with other content", () => {
    const markdown = "<details><summary>Inline</summary>body</details> trailing";
    expect(ensureBlankLineAfterDetails(markdown)).toBe(markdown);
  });

  it("returns non-string and empty inputs unchanged", () => {
    expect(ensureBlankLineAfterDetails("")).toBe("");
    expect(ensureBlankLineAfterDetails(undefined)).toBe(undefined);
    expect(ensureBlankLineAfterDetails("no details here")).toBe("no details here");
  });

  it("does not append a trailing blank line at end of content", () => {
    const markdown = "<details>\n<summary>Title</summary>\n\nBody\n\n</details>";
    expect(ensureBlankLineAfterDetails(markdown)).toBe(markdown);
  });
});
