import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const stable = require("./stable.cjs");
const { main } = require("./create_issue.cjs");

describe("stable custom safe-output API", () => {
  let originalEnv;
  let originalGlobals;
  let github;
  let core;
  let context;
  const issue = { number: 42, html_url: "https://github.com/owner/repo/issues/42" };

  beforeEach(() => {
    originalEnv = { ...process.env };
    originalGlobals = { core: global.core, github: global.github, context: global.context };
    for (const key of Object.keys(process.env)) {
      if (key.startsWith("GH_AW_")) delete process.env[key];
    }
    Object.assign(process.env, {
      GH_AW_PROMPTS_DIR: fileURLToPath(new URL("../md/", import.meta.url)),
      GH_AW_WORKFLOW_NAME: "Custom Finding",
      GH_AW_WORKFLOW_ID: "custom-finding",
      GH_AW_CALLER_WORKFLOW_ID: "owner/repo/custom-finding",
      GH_AW_TRACKER_ID: "tracking-123",
      GH_AW_ENGINE_ID: "copilot",
      GH_AW_ENGINE_VERSION: "1.0.0",
      GH_AW_ENGINE_MODEL: "test-model",
      GITHUB_RUN_ID: "123",
    });
    github = {
      hook: { before: vi.fn() },
      rest: { issues: { create: vi.fn().mockResolvedValue({ data: issue }) } },
    };
    core = { info: vi.fn(), debug: vi.fn(), warning: vi.fn(), error: vi.fn(), setOutput: vi.fn() };
    context = { repo: { owner: "owner", repo: "repo" }, runId: 123, serverUrl: "https://github.com", payload: {} };
    stable.setupGlobals(core, github, context, {}, {}, vi.fn());
  });

  afterEach(() => {
    for (const key of Object.keys(process.env)) {
      if (!(key in originalEnv)) delete process.env[key];
    }
    Object.assign(process.env, originalEnv);
    Object.assign(global, originalGlobals);
    vi.restoreAllMocks();
  });

  it("creates an issue with full attribution while preserving trusted custom metadata", async () => {
    const body = "Finding details\n<!-- custom-managed-start -->";
    const result = await stable.createIssue({ title: "Finding", body, labels: ["automation"], assignees: ["maintainer"], type: "Task" });
    expect(result).toEqual({ staged: false, issue });
    const request = github.rest.issues.create.mock.calls[0][0];
    expect(request).toMatchObject({ owner: "owner", repo: "repo", title: "Finding", labels: ["automation"], assignees: ["maintainer"], type: "Task" });
    expect(request.body).toContain(body);
    expect(request.body).toContain("> Generated by [Custom Finding]");
    expect(request.body).toContain("https://github.com/owner/repo/actions/runs/123");
    expect(request.body).toContain("<!-- gh-aw-workflow-id: custom-finding -->");
    expect(request.body).toContain("<!-- gh-aw-workflow-call-id: owner/repo/custom-finding -->");
    expect(request.body).toContain("<!-- gh-aw-tracker-id: tracking-123 -->");
    expect(request.body).toContain(
      "<!-- gh-aw-agentic-workflow: Custom Finding, gh-aw-tracker-id: tracking-123, engine: copilot, version: 1.0.0, model: test-model, id: 123, workflow_id: custom-finding, run: https://github.com/owner/repo/actions/runs/123 -->"
    );
  });

  it("uses exactly the built-in issue body formatting", async () => {
    const parameters = { title: "Finding", body: "Finding details" };
    await stable.createIssue(parameters);
    const customBody = github.rest.issues.create.mock.calls[0][0].body;
    const handler = await main({});
    const result = await handler(parameters);
    expect(result.success).toBe(true);
    expect(github.rest.issues.create.mock.calls[1][0].body).toBe(customBody);
  });

  it("keeps cross-repository attribution on the original enterprise workflow run", async () => {
    context.serverUrl = "https://github.example.com";
    await stable.createIssue({ owner: "other", repo: "target", title: "Finding", body: "Details" });
    const request = github.rest.issues.create.mock.calls[0][0];
    expect(request).toMatchObject({ owner: "other", repo: "target" });
    expect(request.body).toContain("https://github.example.com/owner/repo/actions/runs/123");
    expect(request.body).not.toContain("https://github.example.com/other/target/actions/runs/");
    expect(request.body).toContain("repo%3Aother%2Ftarget");
  });

  it("includes configured headers, installation instructions, triggering context, and warning annotations once", async () => {
    process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({ bodyHeader: "Required header", disclosureHeader: "AI disclosure" });
    process.env.GH_AW_WORKFLOW_SOURCE = "owner/repo/workflow@main";
    process.env.GH_AW_WORKFLOW_SOURCE_URL = "https://github.com/owner/repo/blob/main/workflow.md";
    process.env.GH_AW_DETECTION_CONCLUSION = "warning";
    process.env.GH_AW_DETECTION_REASON = "threat_detected";
    context.payload.issue = { number: 99 };
    await stable.createIssue({ title: "Finding", body: "Unique finding content" });
    const body = github.rest.issues.create.mock.calls[0][0].body;
    expect(body.indexOf("[!CAUTION]")).toBeLessThan(body.indexOf("AI disclosure"));
    expect(body.indexOf("AI disclosure")).toBeLessThan(body.indexOf("Required header"));
    expect(body.indexOf("Required header")).toBeLessThan(body.indexOf("Unique finding content"));
    expect(body.match(/\[!CAUTION\]/g)).toHaveLength(1);
    expect(body).toContain("#99");
    expect(body).toContain("gh aw add owner/repo/workflow@main");
  });

  it("returns a fully attributed staged preview without API writes", async () => {
    process.env.GH_AW_SAFE_OUTPUTS_STAGED = "true";
    const result = await stable.createIssue({ title: "Finding", body: "Details" });
    expect(result.staged).toBe(true);
    expect(result.preview.body).toContain("<!-- gh-aw-workflow-id: custom-finding -->");
    expect(result.preview.body).toContain("> Generated by");
    expect(github.rest.issues.create).not.toHaveBeenCalled();
  });

  it("rejects missing initialization or attribution metadata without API writes", async () => {
    delete global.core;
    await expect(stable.createIssue({ title: "Finding", body: "Details" })).rejects.toThrow("stable.setupGlobals");
    global.core = core;
    for (const key of ["GH_AW_WORKFLOW_ID", "GH_AW_WORKFLOW_NAME"]) {
      const value = process.env[key];
      delete process.env[key];
      await expect(stable.createIssue({ title: "Finding", body: "Details" })).rejects.toThrow("required for custom issue attribution");
      process.env[key] = value;
    }
    expect(github.rest.issues.create).not.toHaveBeenCalled();
  });

  it.each([
    { title: "", body: "Details" },
    { title: "   ", body: "Details" },
    { title: "Finding", body: null },
    { title: "Finding", body: "Details", owner: "" },
  ])("rejects invalid inputs without API writes: %j", async parameters => {
    await expect(stable.createIssue(parameters)).rejects.toThrow("ERR_VALIDATION");
    expect(github.rest.issues.create).not.toHaveBeenCalled();
  });

  it("enforces the exact body limit after attribution, without dropping the footer", async () => {
    process.env.GH_AW_SAFE_OUTPUTS_STAGED = "true";
    const initial = await stable.createIssue({ title: "Finding", body: "x" });
    const overhead = initial.preview.body.length - 1;
    const atLimit = await stable.createIssue({ title: "Finding", body: "x".repeat(65536 - overhead) });
    expect(atLimit.preview.body.length).toBe(65536);
    await expect(stable.createIssue({ title: "Finding", body: "x".repeat(65537 - overhead) })).rejects.toThrow("including attribution");
    expect(github.rest.issues.create).not.toHaveBeenCalled();
  });

  it("propagates API failures rather than reporting success", async () => {
    const error = Object.assign(new Error("Forbidden"), { status: 403 });
    github.rest.issues.create.mockRejectedValue(error);
    await expect(stable.createIssue({ title: "Finding", body: "Details" })).rejects.toThrow("Forbidden");
  });
});
