// Code generated by tests. DO NOT EDIT.

package indexcomparetocontains

import "strings"
import "bytes"

func generatedStringsIndexCheck(s, sub string) bool {
	return strings.Index(s, sub) != -1
}

func generatedBytesIndexCheck(b, sub []byte) bool {
	return bytes.Index(b, sub) != -1
}
