"""Reconcile summaries against raw API records and immutable local Git objects."""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timedelta, timezone
from fractions import Fraction
from io import BytesIO
import json
import math
import os
from pathlib import Path
import re
import subprocess

from statistics_data import DataError, Statistics, count, load_sources, mapping, require, rows, string


WORKFLOW = re.compile(
    r"<!-- (?:gh-aw-agentic-workflow|agentic-workflow|gh-aw-workflow-id|gh-aw-group|gh-aw-expires):"
    r"|^> (?:AI generated|Generated) by (?:Agentic Workflow"
    r"|\[[^\n]+\]\(https://github\.com/[^/\s]+/[^/\s]+/actions/runs/)"
    r"|It was pre-created by \[the workflow run\]", re.MULTILINE,
)
FIXES = re.compile(
    r"^\s*(?:[-*]\s*)?(?:fix(?:es|ed)?|clos(?:e[sd]?|ing)|resolv(?:e[sd]?|ing))"
    r"\s+(?:([\w.-]+/[\w.-]+))?#(\d+)\b", re.IGNORECASE | re.MULTILINE,
)
MACHINE = re.compile(r"(?:^|[-_])(?:bot|machine[-_]user)(?:$|[-_])", re.IGNORECASE)
EXCLUDED = {"node_modules", "vendor", "dist", "fixtures", "testdata", "__fixtures__", "tmp"}
GENERATED_NAME = re.compile(r"(?:\.min\.(?:js|cjs|mjs)$|(?:_generated|\.generated)\.(?:go|js|cjs|mjs)$)")
GENERATED_HEADER = re.compile(
    r"(?im)^\s*(?://|/\*|\*)\s*(?:code generated\b.*do not edit"
    r"|(?:this file is )?(?:auto[- ]generated|generated by)\b)"
)


def jsonl(path: Path) -> list[dict[str, object]]:
    return [mapping(json.loads(line), path.name) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def author(record: dict[str, object]) -> dict[str, object]:
    return {} if record.get("author") is None else mapping(record["author"], "author")


def nodes(record: dict[str, object], key: str) -> list[dict[str, object]]:
    connection = mapping(record.get(key), key)
    result = rows(connection.get("nodes"), key)
    require(count(connection.get("totalCount"), key + ".totalCount") == len(result), f"{key} is truncated")
    return result


def repository(record: dict[str, object]) -> str:
    return string(mapping(record.get("repository"), "repository").get("nameWithOwner"), "nameWithOwner")


def references(body: str, repos: set[str]) -> set[int]:
    return {int(number) for repo, number in FIXES.findall(body) if not repo or repo in repos}


def issue_origin(issue: dict[str, object] | None) -> str:
    if not issue or not author(issue):
        return "unavailable"
    person = author(issue)
    login = string(person.get("login"), "issue author login")
    kind = string(person.get("__typename"), "issue author type")
    if kind == "Bot" and WORKFLOW.search(str(issue.get("body") or "")):
        return "aw"
    if kind == "User" and not MACHINE.search(login):
        return "human"
    return "other"


def percentile(values: list[int], q: Fraction) -> Fraction:
    require(bool(values) and 0 <= q <= 1, "percentile needs a nonempty population and q in [0,1]")
    position = (len(values) - 1) * q
    lower = position.numerator // position.denominator
    return Fraction(values[lower]) + (values[min(lower + 1, len(values) - 1)] - values[lower]) * (position - lower)


def timestamp(value: object) -> datetime:
    result = datetime.fromisoformat(string(value, "timestamp").replace("Z", "+00:00"))
    require(result.utcoffset() is not None, "timestamps must include a timezone")
    return result.astimezone(timezone.utc)


def audit_api(s: Statistics, raw: Path, aliases: tuple[str, ...] = ()) -> None:
    prs = jsonl(raw / "pr-statistics-data.jsonl")
    require(len({count(p.get("number"), "PR number") for p in prs}) == len(prs), "duplicate PR numbers")
    require(len(prs) == s.all_prs.total, "raw PR population differs from summary")
    repos = {s.repository, *aliases}
    cca_prs = [p for p in prs if author(p).get("login") == "copilot-swe-agent"]
    link_records = jsonl(raw / "cca-issue-links.jsonl") if cca_prs else []
    links = {count(p.get("number"), "CCA PR number"): p for p in link_records}
    require(len(links) == len(link_records), "duplicate CCA link records")
    issues: dict[int, dict[str, object] | None] = {}
    for p in link_records:
        for issue in nodes(p, "closingIssuesReferences"):
            if repository(issue) in repos:
                issues[count(issue.get("number"), "issue number")] = issue
    extra = raw / "cca-extra-issues.json"
    if extra.exists():
        for key, value in mapping(json.loads(extra.read_text(encoding="utf-8")), "extra issues").items():
            issues[int(key)] = None if value is None else mapping(value, "extra issue")
    outcomes: dict[int, Counter[str]] = {i: Counter() for i in range(3)}
    components: Counter[str] = Counter()
    elapsed: list[int] = []
    for p in prs:
        login = author(p).get("login")
        body = str(p.get("body") or "")
        origin = 2
        if login == "github-actions" and WORKFLOW.search(body):
            components["direct_aw_prs"] += 1
            origin = 0
        elif login == "copilot-swe-agent":
            number = count(p.get("number"), "PR number")
            require(number in links, f"Missing closing-link inventory for CCA PR #{number}")
            graph = {count(i.get("number"), "issue number") for i in nodes(links[number], "closingIssuesReferences") if repository(i) in repos}
            suffix = body.split("<!-- START COPILOT CODING AGENT SUFFIX -->")
            suffix_refs = references(suffix[-1], repos) if len(suffix) > 1 else set()
            refs = suffix_refs or graph | references(body, repos)
            require(refs <= issues.keys(), f"Missing cached issue metadata for PR #{number}: {sorted(refs - issues.keys())}")
            refs = {n for n in refs if not (issues[n] or {}).get("not_an_issue")}
            origins = {issue_origin(issues[n]) for n in refs}
            if not refs:
                components["cca_no_issue_assumed_human_prs"] += 1
                origin = 1
            elif origins == {"aw"}:
                components["cca_aw_issue_prs"] += 1
                origin = 0
            elif origins == {"human"}:
                components["cca_human_issue_prs"] += 1
                origin = 1
        state = string(p.get("state"), "PR state")
        require(state in {"MERGED", "CLOSED", "OPEN"}, "unknown PR state")
        created = timestamp(p.get("createdAt"))
        require(created.date() <= s.snapshot, "PR creation is after the declared snapshot date")
        require((state == "MERGED") == (p.get("mergedAt") is not None), "PR state contradicts mergedAt")
        outcomes[origin][state] += 1
        if state == "MERGED":
            delta = timestamp(p["mergedAt"]) - created
            micros = (delta.days * 86400 + delta.seconds) * 1000000 + delta.microseconds
            require(micros >= 0, "merge precedes PR creation")
            elapsed.append(micros)
    for i, expected in enumerate(s.outcomes):
        require((outcomes[i]["MERGED"], outcomes[i]["CLOSED"], outcomes[i]["OPEN"]) ==
                (expected.merged, expected.closed, expected.opened), f"raw outcomes disagree for {expected.label}")
    for key in ("direct_aw_prs", "cca_aw_issue_prs", "cca_human_issue_prs", "cca_no_issue_assumed_human_prs"):
        require(components[key] == s.components[key], f"raw provenance disagrees for {key}")
    elapsed.sort()
    hours = [Fraction(value, 3600000000) for value in elapsed]
    for bucket in s.bins:
        lower = Fraction(str(bucket.lower))
        upper = None if bucket.upper is None else Fraction(str(bucket.upper))
        actual = sum(value >= lower and (upper is None or value < upper) for value in hours)
        require(actual == bucket.count, f"raw duration counts disagree for {bucket.label}")
    if elapsed:
        require(s.median_hours is not None and s.p90_hours is not None, "missing timing quantiles")
        for q, expected_quantile in ((Fraction(1, 2), s.median_hours), (Fraction(9, 10), s.p90_hours)):
            actual_hours = percentile(elapsed, q) / 3600000000
            require(expected_quantile is not None and math.isclose(float(actual_hours), expected_quantile, rel_tol=1e-12, abs_tol=1e-9), "raw timing quantile disagrees")

    issues_raw = jsonl(raw / "community-issues-data.jsonl")
    require(len({count(i.get("number"), "issue number") for i in issues_raw}) == len(issues_raw), "duplicate community issues")
    require(all(i.get("state") in {"OPEN", "CLOSED"} for i in issues_raw), "unknown community issue state")
    eligible = [i for i in issues_raw if author(i).get("__typename") == "User"
                and i.get("authorAssociation") in {"NONE", "CONTRIBUTOR", "FIRST_TIMER", "FIRST_TIME_CONTRIBUTOR"}]
    delivery: dict[int, dict[str, object]] = {}
    landed = 0
    for issue in eligible:
        prs_main = [p for p in nodes(issue, "closedByPullRequestsReferences")
                    if p.get("mergedAt") and p.get("baseRefName") == "main" and repository(p) == s.repository]
        if prs_main:
            require(issue.get("state") == "CLOSED", "landed issue is open; the disjoint community partition needs review")
            landed += 1
        for p in prs_main:
            number = count(p.get("number"), "delivery PR number")
            if number in delivery:
                previous = delivery[number]
                require(timestamp(p["mergedAt"]) == timestamp(previous["mergedAt"]) and author(p).get("login") == author(previous).get("login"),
                        f"Conflicting metadata for delivery PR #{number}")
            timestamp(p["mergedAt"])
            delivery[number] = p
    expected_community = (s.labelled_issues, s.eligible_issues, s.authors, s.landed, s.closed_no_link, s.open_issues, s.delivery_prs, s.cca_delivery)
    actual_community = (len(issues_raw), len(eligible), len({string(author(i).get("login"), "community author") for i in eligible}), landed,
              sum(i.get("state") == "CLOSED" for i in eligible) - landed,
              sum(i.get("state") == "OPEN" for i in eligible), len(delivery),
              sum(author(p).get("login") == "copilot-swe-agent" for p in delivery.values()))
    require(actual_community == expected_community, f"raw community counts disagree: {actual_community} != {expected_community}")


def git(repo: Path, args: list[str], stdin: bytes | None = None) -> bytes:
    env = {**os.environ, "GIT_NO_LAZY_FETCH": "1", "GIT_TERMINAL_PROMPT": "0"}
    try:
        result: subprocess.CompletedProcess[bytes] = subprocess.run(
            ["git", "-C", str(repo), *args], input=stdin, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, check=True, env=env,
        )
    except subprocess.CalledProcessError as error:
        detail = error.stderr.decode("utf-8", errors="replace") if isinstance(error.stderr, bytes) else str(error.stderr)
        raise DataError(f"Local Git audit failed (no fetch attempted): {detail.strip()}") from error
    return result.stdout


def excluded(path: str) -> bool:
    return bool(set(Path(path).parts) & EXCLUDED or GENERATED_NAME.search(path))


def group_key(path: str) -> tuple[str, str]:
    name = Path(path).name
    tests = (name.endswith("_test.go") or re.search(r"\.(?:test|spec)\.(?:js|cjs|mjs|jsx)$", name)
             or set(Path(path).parts) & {"test", "tests", "__tests__", "testutil", "testutils"}
             or name.startswith(("test-", "test_", "fuzz_")))
    return ("Go" if path.endswith(".go") else "JavaScript", "Tests" if tests else "Implementation")


def audit_git(s: Statistics, repo: Path) -> None:
    require(git(repo, ["rev-parse", "--is-shallow-repository"]).strip() == b"false", "Git audit requires complete, non-shallow history")
    blobs: list[tuple[str, str]] = []
    for entry in git(repo, ["ls-tree", "-rz", s.commit]).split(b"\0"):
        if not entry:
            continue
        info, path_bytes = entry.split(b"\t", 1)
        _, kind, oid = info.split()
        path = path_bytes.decode("utf-8")
        if kind == b"blob" and path.endswith((".go", ".js", ".cjs", ".mjs", ".jsx")) and not excluded(path):
            blobs.append((path, oid.decode("ascii")))
    payload = BytesIO(git(repo, ["cat-file", "--batch"], "\n".join(oid for _, oid in blobs).encode("ascii") + b"\n")) if blobs else BytesIO()
    totals: dict[tuple[str, str], list[int]] = {}
    generated: set[str] = set()
    physical = 0
    for path, _ in blobs:
        header = payload.readline().split()
        require(len(header) == 3 and header[1] == b"blob", f"Blob unavailable locally: {path}; no fetch attempted")
        size = int(header[2])
        body = payload.read(size)
        require(len(body) == size and payload.read(1) == b"\n", "truncated Git blob stream")
        content = body.decode("utf-8")
        if GENERATED_HEADER.search("\n".join(content.splitlines()[:30])) or (
            path.endswith((".js", ".cjs", ".mjs")) and re.search(r"\b(?:__commonJS|__webpack_modules__)\b", content[:2000])
        ):
            generated.add(path)
            continue
        lines = content.splitlines()
        key = group_key(path)
        counts = totals.setdefault(key, [0, 0])
        counts[0] += 1
        counts[1] += sum(bool(line.strip()) for line in lines)
        physical += len(lines)
    for group in s.groups:
        require(totals.get((group.language, group.role), [0, 0]) == [group.files, group.lines],
                f"pinned Git code counts disagree for {group.language} {group.role}")
    weekly: dict[str, list[int]] = {}
    current = ""
    log = git(repo, ["log", s.commit, "--first-parent", "--diff-merges=first-parent", "--no-renames",
                     "--format=%x1e%cI%x00", "--numstat", "-z", "--", "*.go", "*.js", "*.cjs", "*.mjs", "*.jsx"])
    for chunk in log.split(b"\0"):
        chunk = chunk.lstrip(b"\n")
        if not chunk:
            continue
        if chunk.startswith(b"\x1e"):
            day = timestamp(chunk[1:].decode("ascii")).date()
            current = (day - timedelta(days=day.weekday())).isoformat()
            continue
        added, deleted, path_bytes = chunk.split(b"\t", 2)
        path = path_bytes.decode("utf-8")
        if added == b"-" or deleted == b"-" or excluded(path) or path in generated:
            continue
        totals_week = weekly.setdefault(current, [0, 0])
        totals_week[0] += int(added)
        totals_week[1] += int(deleted)
    require(set(weekly) <= {week.start.isoformat() for week in s.weeks}, "Git history has weeks omitted from the summary")
    for week in s.weeks:
        require(weekly.get(week.start.isoformat(), [0, 0]) == [week.added, week.deleted], f"Git totals disagree for {week.start}")
    require(sum(w.added - w.deleted for w in s.weeks) == physical, "history net differs from pinned physical lines, including blanks")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--input", type=Path)
    source.add_argument("--data-dir", type=Path)
    parser.add_argument("--raw-dir", type=Path, required=True)
    parser.add_argument("--repo", type=Path, help="Optional local, complete clone for immutable code/history verification.")
    parser.add_argument("--repository-alias", action="append", default=[], help="Explicit migration alias sharing the same issue number namespace.")
    args = parser.parse_args()
    try:
        s = Statistics.from_sources(load_sources(args.data_dir or args.input, args.data_dir is not None))
        audit_api(s, args.raw_dir, tuple(args.repository_alias))
        if args.repo is not None:
            audit_git(s, args.repo)
    except (DataError, OSError, ValueError) as error:
        parser.error(str(error))
    print("Raw API counts, inferred provenance, every timing bin and quantiles reconcile.")
    if args.repo is not None:
        print("Pinned Git code groups, every weekly pair and physical-line net reconcile; no network access used.")
    print("Consistency verified; session initiation, human identity, causality and released impact remain unproven.")


if __name__ == "__main__":
    main()
