//go:build !integration

package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/github/gh-aw/pkg/parser"
	"github.com/github/gh-aw/pkg/workflow"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestStatusCompiledImmediatelyAfterCompile(t *testing.T) {
	tmpDir := t.TempDir()
	t.Chdir(tmpDir)
	workflowDir := filepath.Join(".github", "workflows")
	require.NoError(t, os.MkdirAll(filepath.Join(workflowDir, "shared"), 0755))
	mdPath := filepath.Join(workflowDir, "test-workflow.md")
	lockPath := filepath.Join(workflowDir, "test-workflow.lock.yml")
	require.NoError(t, os.WriteFile(mdPath, []byte(`---
on: workflow_dispatch
engine: copilot
---
# Test Workflow
{{#runtime-import shared/context.md}}
`), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(workflowDir, "shared", "context.md"), []byte("Use ${{ github.repository }}."), 0644))

	compiler := workflow.NewCompiler()
	compiler.SetQuiet(true)
	absolutePath, err := filepath.Abs(mdPath)
	require.NoError(t, err)
	require.NoError(t, compiler.CompileWorkflow(absolutePath))
	assert.Equal(t, "Yes", isCompiledUpToDate(mdPath, lockPath))
	assert.Equal(t, "Yes", isCompiledUpToDate(absolutePath, lockPath))

	t.Setenv("PATH", tmpDir)
	statuses, err := GetWorkflowStatuses(t.Context(), "test-workflow", "", "", "")
	require.NoError(t, err)
	require.Len(t, statuses, 1)
	assert.Equal(t, "Yes", statuses[0].Compiled)

	require.NoError(t, os.WriteFile(filepath.Join(workflowDir, "shared", "context.md"), []byte("Use ${{ github.run_id }}."), 0644))
	assert.Equal(t, "No", isCompiledUpToDate(mdPath, lockPath))
	require.NoError(t, compiler.CompileWorkflow(absolutePath))
	assert.Equal(t, "Yes", isCompiledUpToDate(mdPath, lockPath))

	promptPath := filepath.Join(workflowDir, "shared", "context.md")
	targetPath := filepath.Join(tmpDir, workflowDir, "shared", "target.md")
	require.NoError(t, os.WriteFile(targetPath, []byte("Use ${{ github.run_id }}."), 0644))
	require.NoError(t, os.Remove(promptPath))
	require.NoError(t, os.Symlink(targetPath, promptPath))
	assert.Equal(t, "Yes", isCompiledUpToDate(mdPath, lockPath), "An absolute-target symlink inside .github should hash identically")
}

func TestStatusCompiledBodyHash(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"true", "full"} {
		t.Run(mode, func(t *testing.T) {
			tmpDir := t.TempDir()
			mdPath := filepath.Join(tmpDir, "test.md")
			lockPath := filepath.Join(tmpDir, "test.lock.yml")
			content := "---\non:\n  workflow_dispatch:\n  stale-check: " + mode + "\nengine: copilot\n---\nOriginal body.\n"
			require.NoError(t, os.WriteFile(mdPath, []byte(content), 0644))
			compiler := workflow.NewCompiler()
			compiler.SetQuiet(true)
			require.NoError(t, compiler.CompileWorkflow(mdPath))
			assert.Equal(t, "Yes", isCompiledUpToDate(mdPath, lockPath))

			require.NoError(t, os.WriteFile(mdPath, []byte(content+"Changed body.\n"), 0644))
			expected := "Yes"
			if mode == "full" {
				expected = "No"
			}
			assert.Equal(t, expected, isCompiledUpToDate(mdPath, lockPath))
			require.NoError(t, compiler.CompileWorkflow(mdPath))
			assert.Equal(t, "Yes", isCompiledUpToDate(mdPath, lockPath))
		})
	}
}

func TestIsCompiledUpToDate(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()

	// Minimal valid workflow markdown
	mdContent := `---
name: test-workflow
on:
  workflow_dispatch:
engine: copilot
---

# Test Workflow

A simple test workflow.
`

	mdPath := filepath.Join(tmpDir, "test-workflow.md")
	require.NoError(t, os.WriteFile(mdPath, []byte(mdContent), 0644), "Should write test workflow")

	// Compute the real frontmatter hash for the test markdown
	cache := parser.NewImportCache("")
	realHash, err := parser.ComputeFrontmatterHashFromFile(mdPath, cache)
	require.NoError(t, err, "Should compute frontmatter hash")

	t.Run("matching hash returns Yes", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "test-workflow.lock.yml")
		lockContent := `# gh-aw-metadata: {"schema_version":"v1","frontmatter_hash":"` + realHash + `"}
name: test-workflow
`
		require.NoError(t, os.WriteFile(lockPath, []byte(lockContent), 0644), "Should write lock file")

		result := isCompiledUpToDate(mdPath, lockPath)
		assert.Equal(t, "Yes", result, "Matching hash should return Yes")
	})

	t.Run("mismatched hash returns No", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "mismatched.lock.yml")
		lockContent := `# gh-aw-metadata: {"schema_version":"v1","frontmatter_hash":"0000000000000000000000000000000000000000000000000000000000000000"}
name: test-workflow
`
		require.NoError(t, os.WriteFile(lockPath, []byte(lockContent), 0644), "Should write lock file")

		result := isCompiledUpToDate(mdPath, lockPath)
		assert.Equal(t, "No", result, "Mismatched hash should return No")
	})

	t.Run("legacy lock file without hash returns No", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "legacy.lock.yml")
		lockContent := `#
# This file was automatically generated by gh-aw. DO NOT EDIT.
#
name: test-workflow
`
		require.NoError(t, os.WriteFile(lockPath, []byte(lockContent), 0644), "Should write legacy lock file")

		result := isCompiledUpToDate(mdPath, lockPath)
		assert.Equal(t, "No", result, "Unverifiable lock file should return No, matching activation")
	})

	t.Run("nonexistent lock file returns No", func(t *testing.T) {
		result := isCompiledUpToDate(mdPath, filepath.Join(tmpDir, "nonexistent.lock.yml"))
		assert.Equal(t, "No", result, "Nonexistent lock file should return No")
	})

	t.Run("unreadable source returns No", func(t *testing.T) {
		lockPath := filepath.Join(tmpDir, "unreadable.lock.yml")
		require.NoError(t, os.WriteFile(lockPath, []byte(`# gh-aw-metadata: {"schema_version":"v4","frontmatter_hash":"`+realHash+`"}`), 0644))
		assert.Equal(t, "No", isCompiledUpToDate(filepath.Join(tmpDir, "missing.md"), lockPath))
	})
}
