name: 'Copilot Client'
description: 'Execute Copilot client with comprehensive logging'

inputs:
  config-file:
    description: 'Path to the copilot client configuration JSON file'
    required: true
  event-log-file:
    description: 'Path where event log should be written (JSONL format)'
    required: false
    default: '/tmp/copilot-events.jsonl'
  debug-mode:
    description: 'Enable debug logging'
    required: false
    default: 'false'

outputs:
  exit-code:
    description: 'Exit code from copilot-client execution'
    value: ${{ steps.run-copilot-client.outputs.exit_code }}
  events-count:
    description: 'Number of events logged'
    value: ${{ steps.verify-output.outputs.events_count }}

runs:
  using: "composite"
  steps:
    - name: Verify Prerequisites
      shell: bash
      run: |
        echo "=== Copilot Client Prerequisites Check ===" | tee -a copilot-client.log
        echo "Timestamp: $(date -Iseconds)" | tee -a copilot-client.log
        echo "Working directory: $(pwd)" | tee -a copilot-client.log
        echo "" | tee -a copilot-client.log
        
        echo "Checking for copilot-client.js..." | tee -a copilot-client.log
        if [ -f "/opt/gh-aw/copilot/copilot-client.js" ]; then
          FILE_SIZE=$(wc -c < /opt/gh-aw/copilot/copilot-client.js)
          echo "✓ Found copilot-client.js (${FILE_SIZE} bytes)" | tee -a copilot-client.log
        else
          echo "✗ copilot-client.js not found at /opt/gh-aw/copilot/" | tee -a copilot-client.log
          echo "::error::copilot-client.js not found at /opt/gh-aw/copilot/" 
          exit 1
        fi
        
        echo "Checking for configuration file..." | tee -a copilot-client.log
        if [ -f "${{ inputs.config-file }}" ]; then
          CONFIG_SIZE=$(wc -c < "${{ inputs.config-file }}")
          echo "✓ Found config file at ${{ inputs.config-file }} (${CONFIG_SIZE} bytes)" | tee -a copilot-client.log
          echo "Configuration contents:" | tee -a copilot-client.log
          cat "${{ inputs.config-file }}" | tee -a copilot-client.log
        else
          echo "✗ Configuration file not found at ${{ inputs.config-file }}" | tee -a copilot-client.log
          echo "::error::Configuration file not found at ${{ inputs.config-file }}"
          exit 1
        fi
        
        echo "" | tee -a copilot-client.log
        echo "Checking Node.js environment..." | tee -a copilot-client.log
        if command -v node &> /dev/null; then
          NODE_VERSION=$(node --version)
          echo "✓ Node.js version: ${NODE_VERSION}" | tee -a copilot-client.log
        else
          echo "✗ Node.js not found" | tee -a copilot-client.log
          echo "::error::Node.js is not installed"
          exit 1
        fi
        
        echo "" | tee -a copilot-client.log

    - name: Setup Environment
      shell: bash
      run: |
        echo "=== Setting up Copilot Client Environment ===" | tee -a copilot-client.log
        
        # Create event log directory if it doesn't exist
        EVENT_LOG_DIR=$(dirname "${{ inputs.event-log-file }}")
        echo "Creating event log directory: ${EVENT_LOG_DIR}" | tee -a copilot-client.log
        mkdir -p "${EVENT_LOG_DIR}"
        
        # Ensure event log file can be written
        touch "${{ inputs.event-log-file }}" || {
          echo "::error::Cannot create event log file at ${{ inputs.event-log-file }}"
          exit 1
        }
        echo "✓ Event log file prepared: ${{ inputs.event-log-file }}" | tee -a copilot-client.log
        
        echo "" | tee -a copilot-client.log

    - name: Run Copilot Client
      id: run-copilot-client
      shell: bash
      run: |
        echo "=== Running Copilot Client ===" | tee -a copilot-client.log
        echo "Timestamp: $(date -Iseconds)" | tee -a copilot-client.log
        echo "Configuration: ${{ inputs.config-file }}" | tee -a copilot-client.log
        echo "Event log: ${{ inputs.event-log-file }}" | tee -a copilot-client.log
        echo "Debug mode: ${{ inputs.debug-mode }}" | tee -a copilot-client.log
        echo "" | tee -a copilot-client.log
        
        # Set debug environment variable if requested
        if [ "${{ inputs.debug-mode }}" = "true" ]; then
          export DEBUG="copilot-client"
          echo "Debug logging enabled" | tee -a copilot-client.log
        fi
        
        # Execute copilot-client
        echo "Executing: cat ${{ inputs.config-file }} | node /opt/gh-aw/copilot/copilot-client.js" | tee -a copilot-client.log
        echo "Starting execution at $(date -Iseconds)..." | tee -a copilot-client.log
        
        START_TIME=$(date +%s)
        EXIT_CODE=0
        
        # Capture both stdout and stderr
        cat "${{ inputs.config-file }}" | node /opt/gh-aw/copilot/copilot-client.js 2>&1 | tee -a copilot-client.log || EXIT_CODE=$?
        
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        
        echo "" | tee -a copilot-client.log
        echo "Execution completed at $(date -Iseconds)" | tee -a copilot-client.log
        echo "Duration: ${DURATION} seconds" | tee -a copilot-client.log
        echo "Exit code: ${EXIT_CODE}" | tee -a copilot-client.log
        echo "" | tee -a copilot-client.log
        
        # Set output
        echo "exit_code=${EXIT_CODE}" >> $GITHUB_OUTPUT
        
        # Return with the captured exit code
        if [ ${EXIT_CODE} -ne 0 ]; then
          echo "::warning::Copilot client exited with code ${EXIT_CODE}"
        else
          echo "✓ Copilot client completed successfully" | tee -a copilot-client.log
        fi
        
        exit ${EXIT_CODE}

    - name: Verify Output
      id: verify-output
      if: always()
      shell: bash
      run: |
        echo "=== Verifying Copilot Client Output ===" | tee -a copilot-client.log
        
        if [ -f "${{ inputs.event-log-file }}" ]; then
          FILE_SIZE=$(wc -c < "${{ inputs.event-log-file }}")
          EVENTS_COUNT=$(wc -l < "${{ inputs.event-log-file }}")
          echo "✓ Event log exists: ${{ inputs.event-log-file }}" | tee -a copilot-client.log
          echo "  File size: ${FILE_SIZE} bytes" | tee -a copilot-client.log
          echo "  Events logged: ${EVENTS_COUNT}" | tee -a copilot-client.log
          echo "" | tee -a copilot-client.log
          
          # Set output
          echo "events_count=${EVENTS_COUNT}" >> $GITHUB_OUTPUT
          
          # Show first few events if debug mode is enabled
          if [ "${{ inputs.debug-mode }}" = "true" ] && [ ${EVENTS_COUNT} -gt 0 ]; then
            echo "First 5 events:" | tee -a copilot-client.log
            head -5 "${{ inputs.event-log-file }}" | tee -a copilot-client.log
            echo "" | tee -a copilot-client.log
          fi
          
          # Validate JSONL format (each line should be valid JSON)
          echo "Validating JSONL format..." | tee -a copilot-client.log
          INVALID_LINES=0
          while IFS= read -r line; do
            if ! echo "$line" | jq empty 2>/dev/null; then
              INVALID_LINES=$((INVALID_LINES + 1))
            fi
          done < "${{ inputs.event-log-file }}"
          
          if [ ${INVALID_LINES} -eq 0 ]; then
            echo "✓ All ${EVENTS_COUNT} events are valid JSON" | tee -a copilot-client.log
          else
            echo "⚠ Found ${INVALID_LINES} invalid JSON lines" | tee -a copilot-client.log
            echo "::warning::Found ${INVALID_LINES} invalid JSON lines in event log"
          fi
        else
          echo "⚠ Event log file not found: ${{ inputs.event-log-file }}" | tee -a copilot-client.log
          echo "::warning::Event log file was not created"
          echo "events_count=0" >> $GITHUB_OUTPUT
        fi
        
        echo "" | tee -a copilot-client.log

    - name: Upload Copilot Client Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: copilot-client-logs-${{ github.run_id }}
        path: |
          copilot-client.log
          ${{ inputs.event-log-file }}
        if-no-files-found: ignore

    - name: Execution Summary
      if: always()
      shell: bash
      run: |
        echo "=== Copilot Client Execution Summary ===" | tee -a copilot-client.log
        echo "Completed at: $(date -Iseconds)" | tee -a copilot-client.log
        echo "Exit code: ${{ steps.run-copilot-client.outputs.exit_code }}" | tee -a copilot-client.log
        echo "Events logged: ${{ steps.verify-output.outputs.events_count }}" | tee -a copilot-client.log
        echo "Full logs available in copilot-client.log" | tee -a copilot-client.log
        echo "" | tee -a copilot-client.log
        
        if [ "${{ steps.run-copilot-client.outputs.exit_code }}" = "0" ]; then
          echo "✓ Copilot client execution successful" | tee -a copilot-client.log
        else
          echo "✗ Copilot client execution failed" | tee -a copilot-client.log
        fi
