import assert from "node:assert/strict";
import { test } from "node:test";
import { activeAgent, buildQueue, classify, fetchActiveRuns, fetchCandidate, formatSummary } from "./pr-sous-chef.mjs";

const now = Date.parse("2026-10-03T18:00:00Z");
const recent = "2026-10-03T16:00:00Z";
const pr = {
  number: 42,
  title: "Fix a bug",
  state: "OPEN",
  author: { login: "Copilot" },
  headRefOid: "abc",
  headRefName: "copilot/fix",
  createdAt: "2026-10-01T00:00:00Z",
  updatedAt: recent,
  changedFiles: 2,
  mergeStateStatus: "CONFLICTING",
  statusCheckRollup: [],
};

function detail(threads = []) {
  return {
    commits: { nodes: [{ commit: { committedDate: recent } }] },
    reviewThreads: { nodes: threads, pageInfo: { hasNextPage: false } },
    reviews: { nodes: [], pageInfo: { hasPreviousPage: false } },
  };
}

function nudge(state, at = "2026-10-03T16:30:00Z") {
  return {
    id: 123,
    user: { login: "gh-aw-bot" },
    created_at: at,
    body: `@copilot fix conflicts\nSous-chef state: ${state}`,
  };
}

function thread(overrides = {}) {
  return {
    id: "PRRT_example",
    isResolved: false,
    comments: {
      pageInfo: { hasNextPage: false },
      nodes: [
        {
          author: { login: "reviewer" },
          authorAssociation: "MEMBER",
          body: "Fix the regression",
          createdAt: recent,
          updatedAt: recent,
          url: "https://github.com/github/gh-aw/pull/42#discussion_r1",
        },
      ],
    },
    ...overrides,
  };
}

test("unchanged conflicts never get a repeat poke, even after cooldown", () => {
  const first = classify(pr, detail(), [], [], now);
  assert.ok(first.state_fingerprint);
  const comments = [nudge(first.state_fingerprint)];
  assert.equal(classify(pr, detail(), comments, [], now).skip_reason, "unchanged");
  assert.equal(classify(pr, detail(), comments, [], now + 24 * 60 * 60 * 1000).skip_reason, "unchanged");
});

test("visible fingerprint survives HTML marker removal and arbitrary comment order", () => {
  const first = classify(pr, detail(), [], [], now);
  const reply = {
    id: 124,
    user: { login: "Copilot" },
    created_at: "2026-10-03T17:00:00Z",
    body: "Already addressed; awaiting maintainer CI",
  };
  for (const comments of [
    [reply, nudge(first.state_fingerprint)],
    [nudge(first.state_fingerprint), reply],
  ]) {
    assert.equal(classify(pr, detail(), comments, [], now).skip_reason, "unchanged");
  }
});

test("new HEAD and changed blockers can advance again", () => {
  const first = classify(pr, detail(), [], [], now);
  const comments = [nudge(first.state_fingerprint)];
  assert.ok(classify({ ...pr, headRefOid: "def" }, detail(), comments, [], now).state_fingerprint);
  assert.ok(classify(pr, detail([thread()]), comments, [], now).state_fingerprint);
});

test("bot replies and updatedAt churn are not progress", () => {
  const first = classify(pr, detail(), [], [], now);
  const comments = [nudge(first.state_fingerprint), { user: { login: "github-actions[bot]" }, created_at: recent, body: "Report updated" }];
  assert.equal(classify({ ...pr, updatedAt: "2026-10-03T17:59:00Z" }, detail(), comments, [], now).skip_reason, "unchanged");
});

test("legacy provenance without a hidden marker suppresses unchanged PRs", () => {
  const comment = nudge("unused");
  comment.body = "@copilot run pr-finisher\n> Generated by [PR Sous Chef](https://github.com/github/gh-aw/actions/runs/1)";
  assert.equal(classify({ ...pr, mergeStateStatus: "BLOCKED" }, detail(), [comment], [], now).skip_reason, "unchanged_legacy");
});

test("latest legacy nudge is selected by timestamp, not REST array order", () => {
  const older = { ...nudge("unused", "2026-10-03T15:00:00Z"), body: "<!-- gh-aw-pr-sous-chef-nudge --> @copilot fix" };
  const newer = { ...older, created_at: "2026-10-03T16:30:00Z" };
  assert.equal(classify({ ...pr, mergeStateStatus: "BLOCKED" }, detail(), [older, newer], [], now).skip_reason, "unchanged_legacy");
});

test("legacy nudges do not suppress newly actionable blockers", () => {
  const legacy = { ...nudge("unused"), body: "<!-- gh-aw-pr-sous-chef-nudge --> @copilot fix" };
  assert.ok(classify({ ...pr, mergeStateStatus: "CONFLICTING" }, detail(), [legacy], [], now).state_fingerprint);
  assert.ok(classify({ ...pr, mergeStateStatus: "BEHIND" }, detail(), [legacy], [], now).state_fingerprint);
  assert.ok(classify({ ...pr, mergeStateStatus: "BLOCKED", statusCheckRollup: [{ name: "CGO", status: "COMPLETED", conclusion: "FAILURE" }] }, detail(), [legacy], [], now).state_fingerprint);
});

test("dependency bots are ignored using all known login formats", () => {
  for (const author of ["dependabot[bot]", "app/dependabot", "dependabot", "renovate[bot]", "app/renovate"]) {
    assert.equal(classify({ ...pr, author: { login: author } }, detail(), [], [], now).skip_reason, "dependency_bot");
  }
});

test("bot comments cannot revive a completely stale PR", () => {
  const stale = detail();
  stale.commits.nodes[0].commit.committedDate = "2026-09-01T00:00:00Z";
  const comments = [{ user: { login: "Copilot" }, body: "status", created_at: recent }];
  assert.equal(classify(pr, stale, comments, [], now).skip_reason, "stale");
});

test("fresh human feedback revives an older PR", () => {
  const stale = detail([thread()]);
  stale.commits.nodes[0].commit.committedDate = "2026-09-01T00:00:00Z";
  assert.ok(classify(pr, stale, [], [], now).state_fingerprint);
});

test("an active coding agent blocks even an old run on a previous SHA", () => {
  for (const status of ["queued", "in_progress", "pending", "requested", "waiting"]) {
    const run = {
      name: "Copilot cloud agent",
      status,
      head_branch: pr.headRefName,
      head_sha: "old",
      created_at: "2026-09-01T00:00:00Z",
    };
    assert.equal(classify(pr, detail(), [], [run], now).skip_reason, "agent_active");
  }
  assert.equal(activeAgent(pr, [{ name: "Copilot cloud agent", status: "completed", head_branch: pr.headRefName }]), false);
});

test("active reviewer workflows block duplicate sous-chef work", () => {
  for (const name of ["PR Code Quality Reviewer", "Ponytail Reviewer"]) {
    assert.equal(activeAgent(pr, [{ name, status: "queued", head_branch: pr.headRefName }]), true);
  }
});

test("active agents match PR number even without a branch match", () => {
  assert.equal(activeAgent(pr, [{ name: "Q", status: "in_progress", pull_requests: [{ number: 42 }] }]), true);
});

test("long-running agent checks never age out", () => {
  const checks = [{ name: "Copilot coding agent", status: "IN_PROGRESS", startedAt: "2026-09-01T00:00:00Z" }];
  assert.equal(classify({ ...pr, statusCheckRollup: checks }, detail(), [], [], now).skip_reason, "agent_active");
});

test("short pending CI gates, WAITING CI remains directly approvable", () => {
  const checks = [{ name: "CGO", status: "QUEUED", createdAt: "2026-10-03T17:50:00Z" }];
  assert.equal(classify({ ...pr, statusCheckRollup: checks }, detail(), [], [], now).skip_reason, "checks_pending");
  const waiting = classify({ ...pr, statusCheckRollup: [{ name: "CGO", status: "WAITING" }] }, detail(), [], [], now);
  assert.equal(waiting.failed_checks[0].conclusion, "ACTION_REQUIRED");
});

test("maintainer Copilot requests also enforce startup cooldown", () => {
  const comments = [{ user: { login: "maintainer" }, author_association: "MEMBER", body: "@copilot run pr-finisher", created_at: "2026-10-03T17:55:00Z" }];
  assert.equal(classify(pr, detail(), comments, [], now).skip_reason, "cooldown");
});

test("DIRTY or BLOCKED alone is not an implementation blocker", () => {
  for (const mergeStateStatus of ["DIRTY", "BLOCKED", "CLEAN", "UNKNOWN"]) {
    assert.equal(classify({ ...pr, mergeStateStatus }, detail(), [], [], now).skip_reason, "nothing_actionable");
  }
  assert.ok(classify({ ...pr, mergeStateStatus: "BEHIND" }, detail(), [], [], now).state_fingerprint);
});

test("check reruns with identical failures do not change the fingerprint", () => {
  const check = { name: "CGO", conclusion: "FAILURE", status: "COMPLETED", detailsUrl: "https://github.com/run/1" };
  const first = classify({ ...pr, statusCheckRollup: [check] }, detail(), [], [], now);
  const second = classify({ ...pr, statusCheckRollup: [{ ...check, detailsUrl: "https://github.com/run/2" }] }, detail(), [nudge(first.state_fingerprint)], [], now);
  assert.equal(second.skip_reason, "unchanged");
});

test("author replies alone do not re-poke an unresolved thread", () => {
  const feedback = thread();
  const first = classify(pr, detail([feedback]), [], [], now);
  feedback.comments.nodes.push({ author: { login: "Copilot" }, body: "Fixed it", createdAt: "2026-10-03T17:00:00Z" });
  assert.equal(classify(pr, detail([feedback]), [nudge(first.state_fingerprint)], [], now).skip_reason, "unchanged");
});

test("truncated review data fails closed", () => {
  const truncated = detail();
  truncated.reviewThreads.pageInfo.hasNextPage = true;
  assert.equal(classify(pr, truncated, [], [], now).skip_reason, "incomplete_reviews");
  const feedback = thread();
  feedback.comments.pageInfo.hasNextPage = true;
  assert.equal(classify(pr, detail([feedback]), [], [], now).skip_reason, "incomplete_reviews");
});

test("resolved feedback permits direct dismissal of stale automation reviews", () => {
  const resolved = detail([thread({ isResolved: true })]);
  resolved.reviews.nodes = [{ author: { login: "github-actions[bot]" }, state: "CHANGES_REQUESTED", databaseId: 8 }];
  const result = classify({ ...pr, mergeStateStatus: "BLOCKED" }, resolved, [], [], now);
  assert.deepEqual(result.dismiss_reviews, [8]);
  assert.deepEqual(result.unresolved_reviews, []);
});

test("GraphQL bot logins without REST suffixes permit review cleanup", () => {
  const resolved = detail();
  resolved.reviews.nodes = [{ author: { login: "github-actions" }, state: "CHANGES_REQUESTED", databaseId: 9 }];
  assert.deepEqual(classify({ ...pr, mergeStateStatus: "BLOCKED" }, resolved, [], [], now).dismiss_reviews, [9]);
});

test("deleted PR authors do not crash classification", () => {
  const authorless = { ...pr, author: null };
  assert.equal(classify(authorless, detail(), [], [], now).author, "unknown");
  assert.equal(classify(authorless, detail([thread()]), [], [], now).author, "unknown");
});

test("external discussion does not change the trusted-state fingerprint", () => {
  const first = classify(pr, detail(), [], [], now);
  const comments = [nudge(first.state_fingerprint), { user: { login: "external" }, author_association: "NONE", body: "Please investigate again", created_at: "2026-10-03T17:00:00Z" }];
  assert.equal(classify(pr, detail(), comments, [], now).skip_reason, "unchanged");
});

test("informational sous-chef acknowledgements made with a maintainer token are not progress", () => {
  const first = classify(pr, detail(), [], [], now);
  const comments = [
    nudge(first.state_fingerprint),
    { user: { login: "maintainer" }, author_association: "MEMBER", body: "Invocation acknowledged\n<!-- gh-aw-workflow-call-id: github/gh-aw/pr-sous-chef -->", created_at: "2026-10-03T17:00:00Z" },
  ];
  assert.equal(classify(pr, detail(), comments, [], now).skip_reason, "unchanged");
});

test("external replies cannot change a trusted review fingerprint", () => {
  const feedback = thread();
  const first = classify(pr, detail([feedback]), [], [], now);
  feedback.comments.nodes.push({ author: { login: "external" }, authorAssociation: "NONE", body: "Try again", createdAt: "2026-10-03T17:00:00Z" });
  assert.equal(classify(pr, detail([feedback]), [nudge(first.state_fingerprint)], [], now).skip_reason, "unchanged");
});

test("out-of-scope unresolved feedback does not wake an implementation agent or dismiss reviews", () => {
  const external = thread();
  external.comments.nodes[0].authorAssociation = "NONE";
  const data = detail([external]);
  data.reviews.nodes = [{ author: { login: "github-actions" }, state: "CHANGES_REQUESTED", databaseId: 9 }];
  assert.equal(classify({ ...pr, mergeStateStatus: "BLOCKED" }, data, [], [], now).skip_reason, "nothing_actionable");
});

test("active-run lookup paginates every nonterminal status", () => {
  const calls = [];
  const runs = fetchActiveRuns("github/gh-aw", args => {
    calls.push(args);
    return [{ workflow_runs: [{ id: 1 }] }, { workflow_runs: [{ id: 2 }] }];
  });
  assert.equal(calls.length, 5);
  assert.equal(runs.length, 10);
  assert.ok(calls.every(args => args.includes("--paginate") && args.includes("--slurp")));
});

test("active-run lookup can be narrowed to one PR branch", () => {
  const calls = [];
  fetchActiveRuns(
    "github/gh-aw",
    args => {
      calls.push(args);
      return [];
    },
    "copilot/fix a bug"
  );
  assert.equal(calls.length, 5);
  assert.ok(calls.every(args => args[1].includes("&branch=copilot%2Ffix%20a%20bug")));
});

test("targeted refresh reads the exact PR without filtering by head owner", () => {
  const calls = [];
  const candidate = fetchCandidate("github/gh-aw", "42", args => {
    calls.push(args);
    return pr;
  });
  assert.equal(candidate.number, 42);
  assert.deepEqual(calls, [["pr", "view", "42", "--repo", "github/gh-aw", "--json", "number,title,url,state,isDraft,headRefOid,headRefName,createdAt,updatedAt,changedFiles,author,mergeStateStatus,statusCheckRollup"]]);
});

test("targeted refresh fails closed when metadata is incomplete or the PR is absent", () => {
  for (const result of [null, { ...pr, number: 43 }, { ...pr, updatedAt: null }, { ...pr, headRefOid: null }]) {
    assert.throws(() => fetchCandidate("github/gh-aw", "42", () => result), /could not refresh PR metadata/);
  }
});

test("deduplication finds a nudge beyond the first hundred comments", () => {
  const first = classify(pr, detail(), [], [], now);
  const comments = Array.from({ length: 130 }, (_, id) => ({
    id,
    user: { login: "github-actions[bot]" },
    body: "Status",
    created_at: recent,
  }));
  comments.push(nudge(first.state_fingerprint));
  assert.equal(classify(pr, detail(), comments, [], now).skip_reason, "unchanged");
});

test("queue selects exactly four PRs with deterministic blocker priority", () => {
  const candidates = Array.from({ length: 6 }, (_, index) => ({ ...pr, number: 48 - index }));
  const queue = buildQueue(
    candidates,
    item => ({
      ...item,
      priority: item.number === 48 ? 0 : 2,
    }),
    now
  );
  assert.deepEqual(
    queue.prs.map(item => item.number),
    [48, 43, 44, 45]
  );
  assert.equal(queue.fetched, 6);
  assert.equal(queue.deferred, 2);
});

test("dependency bots and clearly stale queue entries require no detail reads", () => {
  const queue = buildQueue(
    [
      { ...pr, author: { login: "dependabot[bot]" } },
      { ...pr, number: 43, updatedAt: "2026-09-01T00:00:00Z" },
    ],
    () => assert.fail("No detail API call should be made"),
    now
  );
  assert.equal(queue.prs.length, 0);
  assert.deepEqual(
    queue.skipped.map(item => item.skip_reason),
    ["dependency_bot", "stale"]
  );
});

test("invalid metadata and failed reads are errors, not an empty success queue", () => {
  assert.throws(() => buildQueue([{ ...pr, updatedAt: "bad timestamp" }], () => ({}), now), /Invalid activity timestamp/);
  assert.throws(
    () =>
      buildQueue(
        [pr],
        () => {
          throw new Error("HTTP 403");
        },
        now
      ),
    /HTTP 403/
  );
});

test("eligible context excludes raw successful checks and comment bodies", () => {
  const checks = Array.from({ length: 100 }, (_, index) => ({
    name: `check-${index}`,
    status: "COMPLETED",
    conclusion: "SUCCESS",
  }));
  const result = classify({ ...pr, statusCheckRollup: checks }, detail(), [], [], now);
  assert.ok(result.state_fingerprint);
  assert.equal(result.statusCheckRollup, undefined);
  assert.deepEqual(result.failed_checks, []);
  assert.equal(result.comments, undefined);
});

test("step summary reports skip counts from the queue output", () => {
  const summary = formatSummary({
    fetched: 3,
    prs: [{}],
    deferred: 0,
    skipped: [{ skip_reason: "stale" }, { skip_reason: "stale" }, { skip_reason: "agent_active" }],
  });
  assert.match(summary, /\| stale \| 2 \|/);
  assert.match(summary, /\| agent_active \| 1 \|/);
});
